---
title: "WEB350"
author: "Benjamin Weigel"
date: "10/01/2015"
output:
  pdf_document:
    includes:
      in_header: mystyles.sty
    keep_tex: yes
---

```{r prereq, echo=FALSE, message=FALSE, warning=FALSE}
library(magrittr)
library(nwc.chemsupport)
library(dplyr)
library(Rcpp)
library(stringr)
library(xtable)

options(xtable.comment = FALSE)
options(xtable.booktabs = TRUE)
```

```{r, results='asis', echo=FALSE}
cat("\\tableofcontents\\clearpage")
```

```{r, echo=FALSE, cache=F, message=FALSE, results='asis', warning=FALSE, error=TRUE}
substances <- read.table("~/IPB/thesis/supplementary/WEB350/substances.csv", stringsAsFactors = F, sep = ",", header=T)
v.molmass <- Vectorize(function(x)list(mol.mass(x)$mass))

substances %<>% group_by(name) %>% mutate(formula=toupper(formula), MW=mol.mass(formula)$mass)

dat <- read.csv("~/IPB/thesis/supplementary/fragment.table.csv")
frags <- dat %>% filter(!individual) %>% select(fragment) %>% unlist
indi <- dat %>% filter(individual == T) %>% select(fragment, ring.cleave, mass, substance)

indi[!indi$ring.cleave,3] <- v.molmass(indi[!indi$ring.cleave,1]) %>% unlist

indi %<>% mutate(formula = NA, MW=NA, mz=mass) %>% select(-mass,-ring.cleave)
data <- expand.grid(fragment=frags, substance=substances$name)

data <- merge(data, substances, by.x="substance", by.y="name") %>% 
  group_by(substance, fragment) %>% 
  mutate(mz = frag.mass(fragment, MW))
        
data<-merge(data, indi, all = T)
xtable(head(data))
```

# Automatic annotation of MS spectra #

```{r, echo=FALSE, results='asis', dev='pdf', fig.width=12, fig.height=5, out.width="\\textwidth"}
data.sp <-read.table("~/IPB/thesis/supplementary/WEB350_LCMS.csv", stringsAsFactors = F, sep = ",", header=T)

DIR <- "/media/mori/Stuff/LCMS/WEB2015-III/mzXML/"
#for(i in 1:nrow(data.sp)){
# for(i in 1:5){
#   tmp <- data.sp[i,]
#   mss <- getMSSpec(paste(DIR, tmp$file, sep=""), tmp$scan) 
# 
#   tmp.mm <- data %>% ungroup %>% filter(substance == tmp$name) %>% select(fragment, mz)
#   mm <- massmatch(tmp.mm$mz, mss, tmp.mm$fragment, ppm.in = 10)
#   
#   if(nrow(mm$df)>0){
#     plotSpec(mss, title = paste(tmp$file, ", Compound: ", tmp$name, "\n",
#                                 tmp$method, ".",
#                                 tmp$eV, ".eV, scan ",
#                                 tmp$scan, sep=""), ymax=0.1, relative=T, srt=90)
#     plotANN(mm, adjust = 0.95, relative = T, srt=0)
#     xtable(mm$df, digits = 2) %>% print
#   }
# }
annotations <- list()
for(i in 1:nrow(data.sp)){
  tmp <- data.sp[i,]
  mss <- getMSSpec(paste(DIR, tmp$file, sep=""), tmp$scan) 


  tmp.mm <- data %>% ungroup %>% filter(substance == tmp$name | is.na(substance)) %>% select(fragment, mz)
  mm <- massmatch(tmp.mm$mz, mss, tmp.mm$fragment, ppm.in = 11, thresh = 1)
  
  if(nrow(mm$df)>0){
    cat(paste("\\subsection{",tmp$name,".",tmp$method,".",tmp$eV,"eV}",sep=""))
    plotSpec(mss, title = paste(tmp$file %>% str_replace_all(., pattern = "\\_", "\\\\_"), ", Compound: ", tmp$name, "\n",
                                tmp$method, ".",
                                tmp$eV, ".eV, scan ",
                                tmp$scan, sep=""), relative=T, srt=90, adj=c(0,0.5), yrange=c(-50, 140), rnd=3)
    plotANN(mm, adjust = -0.05, relative = T, lines=T, below=-5, srt=40, adj=c(1,1))
    xtable(mm$df %>% mutate(int=int/mm$maxy*100), digits = c(0,2,1,2,0)) %>% print
    cat("\\clearpage")
    
    nom <- paste(tmp$name, tmp$method, tmp$eV, tmp$type, sep=".")
    x <- list(mm$df %>% mutate(int=int/mm$maxy*100))
    attr(x, "names") <- eval(nom)
    annotations <- append(x, annotations)
  }
}
```


```{r, echo=FALSE, results='asis', message=FALSE}
library(stringr)

comp <- mapply(function(x, i) {
  tmp <- str_split(i, pattern = "[.]") %>% unlist
  x$substance <- rep(tmp[1], nrow(x))
  x$method <- rep(paste(tmp[2],tmp[3],sep="."), nrow(x))
  #x$eV <- rep(tmp[3], nrow(x))
  x$type <- rep(tmp[4], nrow(x))
  list(x)
}, annotations, names(annotations))

comp <- data.table::rbindlist(comp)

comp$substance <- factor(comp$substance, levels = c("naringenin", "eriodictyol", "ponciretin", "hesperetin", "homoeriodictyol",
                                                 "apigenin", "luteolin", "acacetin", "diosmetin", "chrysoeriol",
                                                 "kaempferol", "quercetin", "myricetin", "kaempferide", "isorhamnetin"), ordered = T)
comp$method <- factor(comp$method, levels = c("CID.45", "HCD.75", "HCD.100"), ordered = T)

library(tidyr)
save(comp,file="001_test.Rda")
comp %<>% group_by(fragment, substance, method) %>% #separate(method, into=c("method", "eV"), sep="[.]") %>%  
  mutate(mz.int = if(round(int) == 0)  NA else paste(round(mz), "\\,(", round(int), ")", sep="")) %>% ungroup%>%
  select(fragment, substance, method, mz.int, type)

## load fragment table and calculate masses of fragments
dat <- read.csv("~/IPB/thesis/supplementary/fragment.table.csv")
dat %<>% filter(!individual) %>% select(fragment) %>% group_by(fragment) %>% mutate(delM = abs(frag.mass(fragment, 0)))

#order fragments by mass
dat <- dat[order(dat$delM),]
dat$fragment <- factor(dat$fragment, levels = dat$fragment, ordered = T)

frags <- c("AC+", "0,2A+", "0,2A+-CO", "0,2B+", "0,3A+", "0,3A++2H", "0,4A++2H", "0,4B+", "0,4B+-H2O", 
  "1,3A+", "1,3A+-CO","1,3A+-C2H2O",  "1,3A+-2CO","1,3A+-2CO-C2H4", "1,3B+", "1,3B+-2H", "1,4A++2H", "1,4A.+", "1,4A+",
  "1,4B++2H", "1,4B+-2H", "1,4B++2H-H2O", "1,4B+-2H-H2O", "1,4B+-2H-CO", "1,4B+-2H-CH3-CO", "1,4B+-2H-CO-CH3", "1,4B+-2H-CO-CH2O", "1,4B+-2H-2CO", "1,4B+-2H-2CO-CH3", "1,4B+-2H-C2H2O-H2O",
   "1,4B+-2H-2CO-CH2O", "1,4B+-2H-H2O-CO", "C7H6O5+", "C7H7+", "C7H5+", "C5H5O+", "C3HO2+")

# add indicvidual frags to non-indivdual fragments
frags <- c(as.character(dat$fragment), frags)
#frags <- factor(frags, levels = frags, ordered = T)

x <- comp %>% select(-type) %>% ungroup %>% spread(substance, value = mz.int, fill = NA)
x$method <- factor(x$method, levels = c("CID.45", "HCD.75", "HCD.100"), ordered = T)

x <- x[order(x$method),]
x$fragment <- factor(x$fragment, levels = frags, ordered = T)
x <- x[with(x, order(method, fragment)),] # order data

## convert the fragments
x$fragment %<>% str_replace(., "(\\.\\+)$", "\\^{\\\\bullet\\+}") %>% 
str_replace(., "[+]$", "\\^\\+") %>% str_replace_all(., c("[A][+]"="A\\^\\+", "[B][+]"="B\\^\\+")) %>%
  str_replace_all(., "([HCO])([[:digit:]]+)", "\\1\\_{\\2}") %>%
  #str_replace_all(., "([HCOM[:digit:]+-])([+-])([[:digit:]HCO])", "\\1{\\2}\\3")
  str_replace_all(., "([+-])([[:digit:]HCO])", "{\\1}\\2") %>%
  str_replace_all(., "([,])", "{\\1}")

x$fragment <- paste("$\\mathrm{",x$fragment, "}$", sep="")
#x$fragment <- paste("$",x$fragment, "$", sep="")
###################################

cat("\\setlength\\tabcolsep{1.5pt}")

for(i in unique(x$method)){
  cat("\\begin{sidewaystable}\\caption{Fragment table for method \\textit{", i,"}}", sep="")
  tab<-xtable(x %>% filter(method==i) %>% select(-method), align=c("l", "l|", rep("c", 4), "c|", rep("c", 4), "c|", rep("c", 5)), caption = paste("Fragment table for method:", i))  
  print.xtable(tab, size="\\scriptsize", floating=F, tabular.environment="tabular", include.rownames=T, rotate.colnames = T, booktabs=T, sanitize.text.function = function(x){x}, caption.placement = "top")
  cat("\\end{sidewaystable}\\qquad")
}


```


```{r tab.by.type, results='asis', echo=FALSE}
x <- comp %>% ungroup 

x$fragment <- factor(x$fragment, levels = frags, ordered = T)
x <- x[with(x, order(substance,method,fragment)),] 
#x %<>% unite(., sub.type, substance, method, sep="_") %>% spread(sub.type, value = mz.int, fill=NA)
#x %<>% spread(substance, value = mz.int, fill=NA)
## convert the fragments

#x$fragment <- paste("$",x$fragment, "$", sep="")
###################################
#x <- x[,c(1,2,39,41,40,15,17,16,42,44,43,18,20,19,21,23,22,6,8,7,33,35,34,3,5,4,12,14,13,9,11,10,30,32,31,45,47,46,36,38,37,27,29,28,24,26,25), with=F]

cat("\\setlength\\tabcolsep{1.5pt}")
ORD <- vector("list", 3)
names(ORD) <- unique(x$type)
ORD[[1]] <- c(10,1,13,4,7,12,3,15,6,9,11,2,14,5,8)+1
#ORD[[2]] <- c(4,6,5,13,15,14,1,3,2,10,12,11,7,9,8)+1
ORD[[2]] <- c(4,13,1,10,7,6,15,3,12,9,5,14,2,11,8)+1
#ORD[[3]] <- c(7,9,8,13,15,14,10,12,11,4,6,5,1,3,2)+1
ORD[[3]] <- c(7,13,10,4,1,9,15,12,6,3,8,14,11,5,2)+1
for(i in unique(x$type)){
  tmp <- x %>% filter(type==i)  %>% 
    select(-type) %>% 
    unite(., sub.method, substance, method, sep="\\_") %>% 
    spread(sub.method, value = mz.int, fill=NA)
  tmp <- tmp[,c(1,ORD[[i]]), with=F] 
  
  tmp <- tmp[with(tmp, order(fragment)),] 
  tmp$fragment %<>% str_replace(., "(\\.\\+)$", "\\^{\\\\bullet\\+}") %>% 
    str_replace(., "[+]$", "\\^\\+") %>% str_replace_all(., c("[A][+]"="A\\^\\+", "[B][+]"="B\\^\\+")) %>%
    str_replace_all(., "([HCO])([[:digit:]]+)", "\\1\\_{\\2}") %>%
    #str_replace_all(., "([HCOM[:digit:]+-])([+-])([[:digit:]HCO])", "\\1{\\2}\\3")
    str_replace_all(., "([+-])([[:digit:]HCO])", "{\\1}\\2") %>%
    str_replace_all(., "([,])", "{\\1}")
  
  tmp$fragment <- paste("$\\mathrm{",tmp$fragment, "}$", sep="")
  
  cat("\\begin{sidewaystable}\\caption{Fragment table for type \\textit{", i,"}}", sep="")
  
  #tmp[-(rowSums(!is.na(tmp[,-1,with=F])) == 0),]
  tab<-xtable(tmp, align=c("l", "l|", rep("c", 4), "c|", rep("c", 4), "c|", rep("c", 5)), caption = paste("Fragment table for method:", i))  
  print.xtable(tab, size="\\scriptsize", floating=F, tabular.environment="tabular", include.rownames=T, rotate.colnames = T, booktabs=T, sanitize.text.function = function(x){x}, caption.placement = "top")
  cat("\\end{sidewaystable}")
  }
```

