%%%-------------------------------------------------%%%
%%% Sub document introduction %%%
%%%-------------------------------------------------%%%

\part{Thesis}

\chapter{Introduction}\index{capital letters}

%\capital{S}ome introductionary text

\section{Natural products and secondary metabolites} 

\paragraph{Terpenoids and Steroids} ... here is some text
\paragraph{Polyketides and non-ribosomal peptides} ... here is some text
\paragraph{Alkaloids} ... here is some text
\paragraph{Phenylpropanoids} ... here is some text
Flavonoids and phenyl propanoids have important functions in nature and can function as protection against high UV-exposure, signaling molecules or transcriptional regulators \cite{Grotewold2006,Andersen2006}.

\section{\Glsentryfirst{mt} as tailoring enzymes}



\section{Usage and expansion of natures reaction toolbox}
\subsection{Terpene synthases and elongases}
\subsection{Methyl transferases}
\subsection{Glycosyl transferases}


\section{Conclusion}
