%%%-------------------------------------------------%%%
%%% Sub document introduction %%%
%%%-------------------------------------------------%%%

\part{Thesis}

\chapter{Introduction}\index{capital letters}

%\capital{S}ome introductionary text

\section{Flavonoids} 

\subsection{General}

Plant phenolic compounds account for more than \SI{40}{\percent} of the organic carbon in the biosphere and are essential for the survival of vascular plants.
They are largely derived from the \emph {phenylpropanoid} and relating pathways and take on various structural (e.g. cell walls) and non-structural roles (e.g. plant defense, flower color) \cite{Croteau2000}.
The name \emph{phenylpropanoid} describes the aromatic phenyl connected to a three-carbon chain, which biosynthetically originates from phenylalanine.
Flavonoids, from the Latin \emph{flavus} (yellow), are a diverse subclass of these phenolic compounds comprising more than 4500 different compounds described thus far and their main structural feature is the central chromane (benzodihydropyran) moiety (\autoref{fig:b_flav_struc}).
They consist of three rings named A, B and C.
Ring A and B are of acetate and phenylpropanoid origin respectively, whereas ring C is a result of the condensation of the former.


\begin{figure}[htpb]
  \begin{figureframe}
    \begin{subfigure}{0.23\textwidth}\centering
      \includegraphics[scale=1]{usr/graphics/static/flavonoid_structure}
    \end{subfigure}
    \begin{subfigure}{0.75\textwidth}\centering
      \includegraphics[scale=0.833]{usr/graphics/static/flavonoid_structure2}
    \end{subfigure}
  \end{figureframe}
  \caption{The central feature of the flavonoids is the chromane ring. 
    The names of the different groups of flavonoids are derived from the substitution of this moiety.
    From a biosynthetic point of view, flavonoids are built up from phenylpropanoid (blue) and acetate derived moieties (orange).}
  \label{fig:b_flav_struc}
\end{figure}

Different types of flavonoids are named depending on the substitution pattern of the chromane ring.
For example, a phenyl group at C-2 or C-3 gives flavonoids or isoflavonoids respectively,
an unsubstituted C-4 means flavane, whereas a carbonyl group at C-4 indicates flavan\emph{on}es \textit{et cetera}.
Flavonoids are usually poly-hydroxylated, but can also carry multiple other different substitutions.
%The most common hydroxylations are at positions 5,7,3,3',4',5'.
\textit{O}-methylations are common at all hydroxyl positions, but flavonoids can also be \textit{C}-methylated \cite{Barton1972}. 
Other common derivatizations are (\textit{O} or \textit{C})-prenylation, (\textit{O} or \textit{C})-glycosylation, methylene-dioxy bridges (C-3'/C-4' or C-6/C-7) and various (\textit{O} or \textit{C})-acylations (aliphatic and aromatic acids) \cite{Dagne1990,Wollenweber1985,Simonsen2002,Harborne1988}.

In plants flavonoids are usually produced to combat biotic or abiotic stresses.
They can absorb highly energetic \gls{uv} light, suppress the formation of, or scavange \gls{ros}, once formed \cite{Agati2012}.
Furthermore, flavonoids can act as regulators during plant development \cite{Taylor2005}.
A growing interest in flavonoids for the use in medicinal and nutritional applications has been spiked by their beneficial effects on health.
Flavonoids possess a high antioxidant activity and also show protective effects against age-related ailments, such as cardiovascular diseases and cancers.
Furthermore, they show anti-inflammatory, hepatoprotective, antimicrobial and  antiviral activities \cite{Kumar2013}.

A number of flavonoids are produced by the valorization of wastes and by-products of the food industry. 
Citrus and olive processing byproducts are especially rich in polyphenols \cite{Goodrich2006,Mulinacci2001,Ouallagui2012}.
However, many flavonoids are scarce in nature and/or the production from by-products is not enough to saturate the market demand, thus requiring different approaches for production.
Recent developments in the field of metabolic engineering allowed for the high-level production of many flavonoids in microbial hosts, such as \textit{Escherichia coli} or \textit{Saccharomyces cerevisiae} \cite{Trantas2015}.
For example, eriodictyol was produced from tyrosine in metabolically engineered \eco at levels of up to \SI{107}{\milli\gram\per\milli\litre} \cite{Zhu2014}, whereas naringenin was produced in \scer from glucose at levels of \SI{109}{\milli\gram\per\milli\litre} \cite{Koopman2012}.


\subsection{The phenyl propanoid pathway}

Biosynthesis of flavonoids via the phenylpropanoid pathway starts from phenylalanine, which is non-oxidatively deaminated by \gls{pal} to yield cinnamic acid (\autoref{fig:b_flav_prod}) \cite{Louie2006,Grotewold2006}.
\Gls{c4h}, a P450 monooxygenase, hydroxylates the cinnamic acid at the \textit{para}-position and \gls{4cl} convertes the \textit{p}-coumaric acid to its corresponding \gls{coa}-ester \cite{Urban1994,Hu2010}.
\Gls{chs} uses 3 molecules of malonyl-CoA (produced from acetyl-\gls{coa} by acetyl-\gls{coa} carboxylase) to produce naringenin chalcone from \textit{p}-coumaryl-\gls{coa} \cite{Ferrer1999}.
%The malonyl-\gls{coa} is produced from acetyl-\gls{coa} by acetyl-\gls{coa} carboxylase.
Next, the linear chalcone can cyclize spontaneously or catalyzed by \gls{chi} via a \textsc{Michael}-type addition to afford the flavanone naringenin \cite{Jez2000}.

\begin{figure}[htpb]
  \begin{figureframe}
    \includegraphics[scale=1]{usr/graphics/static/flavonoid_production}
  \end{figureframe}
  \caption{General pathways in the biosynthesis of flavonoids. PAL -- phenylalanin ammonia lyase, C4H -- cinnamate-4-hydroxylase, 4CL -- 4-coumarate:CoA ligase, CHS -- chalcone synthase, CHI -- chalcone isomerase, F3H -- flavanone-3-hydroxylase, FLS -- flavonol synthase, FNS -- flavone synthase, IFS -- isoflavone synthase.}
  \label{fig:b_flav_prod}
\end{figure}

Naringenin can serve as substrate for numerous enzymes such as \gls{f3h}, \gls{fns} or \gls{ifs} to afford dihydroflavonols, flavones or 2-hydroxyisoflavones respectively \cite{Gholami2014}.
Dihydroflavonols are again precursors for the biosynthesis flavonols, flavanols and anthocyani(di)nes.

\subsection{Biological activity}

Flavonoids possess many properties associated with a healthy diet.
They act as antioxidants and can help reduce oxidative stress. %eliminate \gls{ros} in the body.
Several mechanisms that might be involved in the antioxidant activity of flavonoids are currently discussed.
They can act as scavangers for free \gls{ros} or mask metal ions by chelation to suppress the production of radicals \cite{Cao1997,Leopoldini2006}.
The substitution pattern plays an important role in the antioxidant activity.
Generally, the more free hydroxyls are present, the stronger the antioxidant activity of the flavonoid is \cite{Cao1997}.
Hydroxyls can donate an electron, or a hydrogen atom to free \gls{ros} to inactive such molecules.
The resulting flavonoid radicals are stabilized by resonance, however possess prooxidant properties \cite{Metodiewa1999}.
%Flavonoids containing catecholic hydroxyls at the B-ring are even better antioxidants, because they  can donate two hydrogen radicals and be converted into stable 1,2-benzoquinones.

Numerous flavonoids possess antimicrobial activities \cite{Cushnie2005}.
For example, catechins from green and black teas have been shown to be effective against \textit{Bacillus cereus} at nanomolar concentrations \cite{Friedman2006}.
The mechanisms of action can be the inactivation of enzymes, binding of adhesins, membrane disruption or cell wall complexation \cite{Cowan1999}.

\bweigel{ist es sinnvoll hier noch mehr zu schreiben????}

\section{Methyl transferases (MTs)}

\subsection{General}
\Gls{sam}-dependent \mts transfer the methyl group of \sam to an activated atom of an acceptor molecule, via an S\textsubscript{N}2 displacement mechanism.
\Gls{sam} is converted to \gls{sah}, the co-product of the reaction, in the process.
Transfer of the methyl group to oxygen and nitrogen atoms is most common, but carbon, sulfur, selenium, arsenic atoms and even halide ions can be methylated (\autoref{fig:b_methyltransferases})\cite{Thomas2007,Schmidberger2010}.
Acceptor molecules are diverse and range from relatively small natural products (e.g. flavonoids) to bio-macromolecules such as nucleic acids or proteins.
In fact, \glspl{mt} are key-tailoring enzymes for many natural products of all groups (e.g. flavonoids, alkaloids or non-ribosomal peptides) \cite{Kim2010,Kopycki2008b,Struck2012,Wessjohann2013}.
These \glspl{smmt} account for a significant part of the diversity present in natural products.

Other \glspl{mt}, such as \glspl{pmt}, \glspl{dmt} and \glspl{rmt} methylate proteins and nucleic acids respectively.
In eukaryotes, \glspl{dmt} and \glspl{pmt} play important roles in the epigentic regulation of gene expression and have been associated with a number of cancers and other diseases \cite{Copeland2013,Robertson2001,Robertson2005}.
In bacteria, \glspl{dmt} are an essential part of the restriction modification system \cite{McClelland1994}.

According to their structure, \glspl{mt} can be classified into five main groups (I--V) (\autoref{fig:b_mtclasses})\cite{Schubert2003}.
Class I \glspl{mt} are the largest group of \glspl{mt} and are characterized by a central Rossmann-like \textalpha\textbeta\textalpha~sandwich, consisting of a seven-stranded \textbeta-sheet flanked by \textalpha-helices.
Most \glspl{smmt}, \glspl{dmt} and some \glspl{pmt} belong to class I \mts.
Even though some of the enzymes belonging to class I share as little as \SI{10}{\percent} sequence similarity, there is a pronounced structural conservation \cite{Schubert2003}.
Class II \glspl{mt} comprise a long anti-parallel \textbeta-sheet encompassed by numerous \textalpha-helices \cite{Dixon1996}.
In class III \mts the \gls{sam} binding site is located between two \textalpha\textbeta\textalpha~domains \cite{Schubert1998}.
A knot structure at the C-terminus contributes to \sam binding in the \gls{spout} family of class IV \glspl{rmt} \cite{Michel2002}.
Protein lysine \mts make up the largest part of \glspl{pmt} and structurally belong to class V \glspl{mt} containing a \gls{set} domain \cite{Xiao2003}.

\begin{figure}[htpb]
  \begin{figureframe}
    \begin{subfigure}{\textwidth}\centering
      \includegraphics[scale=0.25]{usr/graphics/static/mtclasses}
    \end{subfigure}\vspace{0.4cm}
    \begin{subfigure}{\textwidth}\centering
      \includegraphics[scale=0.25]{usr/graphics/static/topo_rsmt}
    \end{subfigure}      
  \end{figureframe}
  \caption{Topology plots of the five major structural classes of \glspl{mt} and \glsentryfirstplural{rsmt} (modified and extended from Schubert \etal \cite{Schubert2003}). Helices are depicted as circles and \textbeta-strands as triangles. The \sam binding site is depicted as a flag. \Glspl{rsmt} all share a common ``radical SAM''-domain, which cotains the iron sulfur cluster (red checker). The individual \gls{rsmt} classes are differentiated according to the other domains they contain. }
  \label{fig:b_mtclasses}
\end{figure}

Interestingly, a recent study of the methyltransferome of baker's yeast (\textit{S. cerevisiae}) argues, that there are four more different classes of \glspl{mt} \cite{Wlodarski2011}.
Opposite to the studies by Schubert \etal, this work mainly relied on bioinformatical methods for structural information.
83 out of 86 \gls{mt} structures in total were homology-modelled.
It was shown, that two thirds of the reviewed yeast \glspl{mt} belonged to class I.
However, four new folding architectures, namely SSo0622-like, all-\textbeta, all-\textalpha~(RNA/DNA 3-helical bundle) and transmembrane, were postulated.


\begin{figure}[htpb]
  \begin{figureframe}
    \includegraphics[scale=1]{usr/graphics/static/methyl_transferases}
  \end{figureframe}
  \caption{Reactions catalyzed by \glsentryfirstplural{mt}. Different shades of grey were used to differantiate between different groups of compounds and \glspl{mt}. In contrast to other \glspl{mt}, the group of \glspl{rsmt} also requires additional co-factors to \gls{sam}.}
  \label{fig:b_methyltransferases}
\end{figure}


\Glsentryfirstplural{rsmt} comprise another class of resently discovered \glspl{mt} that contain an iron-sulfur ([4Fe-4S])-cluster coordinated by a three cysteine CxxxCxxC motif. \Glspl{rsmt} methylate unreactive centers through a radical mechanism \cite{Werner2011}.
Structural evidence suggests, that the mechanism is initiated by reductive cleavage of \sam into a reactive \gls{dado} radical by the [4Fe-4S] cluster \cite{Boal2011,Broderick2014}. 
Three distinct classes (A, B, C) with distinct structural and mechanistic characteristics have been recognized within the \glspl{rsmt} \cite{Zhang2012a}.
The centerpiece of \glspl{rsmt} is the \emph{radical SAM} domain, whose structure was first described in the \gls{rrna} methyl transferase RlmN of \eco \cite{Boal2011a}.
This domain consists of an \textalpha\textsubscript{6}/\textbeta\textsubscript{6} partial barrel and contains the [4Fe-4S] cluster, as well as the \gls{sam} binding site ({\autoref{fig:b_mtclasses}).
Class A only contains the radical \gls{sam} domain and includes mainly \gls{rrna} methyl transferases. 
In addition to the radical SAM domain, an N-terminal \gls{cbd} is proposed to be contained in \glspl{rsmt} of class B.
Class B \glspl{rsmt} methylate numerous substrates at unreactive sp\textsuperscript{3} carbon centers, heterocycles and phosphinates.
Class C \glspl{rsmt} most likely contain a C-terminal domain related to the coproporphyrinogen III oxidase HemN in addition to the radical SAM domain \cite{Layer2003}.
Class C enzymes methylate aromatic heterocycles.

Radical \gls{sam} chemistry within enzymes is not confined to just methyl transfer. 
Instead, it has been shown that this type of chemistry is important for a number of rearrangement, cyclization, dehydrogenation, bond-formation and bond-cleavage reactions in nature \cite{Broderick2014}.

\subsection{Methyl transferase mechanisms}

\subsection{Plant \glsentryfirstplural{omt}}

%Historically, research on \glspl{omt} has been focused on mammalian \gls{mcomt}, which was the first \gls{omt} described (1958) and structurally characterized (1994) \cite{Vidgren1994,Axelrod1958}.
Plant \glspl{omt} represent a large group of plant enzymes that catalyze the transfer of a methyl group to a hydroxyl or carboxyl group of phenylpropanoids, flavonoids or alkaloids.
\textit{O}-methylation greatly effects the (bio)-chemical properties of a compound and can for example have profound influences on reactivity, solubility, bioavailability, antimicrobial or antioxidant activities.

\Pomts are subdivided into two groups according to their size and the spatial relationship between three highly preserved motifs (\autoref{tab:b_plomts})  \cite{Joshi1998}.
Group I members, containing \gls{ccoaomt}-like representatives, are usually between 110 and 140 amino acid residues shorter than group II members ($\approx$340--390 amino acids).
The distance between motifs A and B, and between B and C is also shorter in group I members, than in group II members.% (\autoref{tab:b_plomts}).
In contrast to group II, group I \pomts require \cf{Mg^2+} for activity. Overall, they are fairly similar to mammalian \glspl{comt} \cite{Joshi1998}.
Group II \pomts can methylate a variety of substrates, whereas group I \pomts are usually very strict in their substrate scope utilizing only a couple of substrates.
However, some enzymes from group I are much more relaxed with their acceptance of substrates.
For example, \gls{pfomt} from the ice-plant \textit{Mesembryanthemum crystallinum} and an \gls{omt} from chickweed \textit{Stellaria longipes} can utilize several substrates \cite{Zhang1997,Ibdah2003}.

\begin{table}[htpb]\centering\small
  \caption{Defining motifs of \pomts as described by Joshi \etal \cite{Joshi1998}.}
  \label{tab:b_plomts}
  \begin{tabular}{llccc}
    \toprule
    motif & consensus & \multicolumn{3}{c}{distance to motif \dots} \\
    \cmidrule(lr){3-5}
    & & \dots & group I & group II \\
    \midrule
    A & (V,I,L)(V,L)(D,K)(V,I)GGXX(G,A) & B & 19 & 52 \\
    B & (V,I,F)(A,P,E)X(A,P,G)DAXXXK(W,Y,F) & C & 24 & 30 \\
    C & (A,P,G,S)(L,I,V)(A,P,G,S)XX(A,P,G,S)(K,R)(V,I)(E,I)(L,I,V) & & & \\
    \bottomrule
  \end{tabular}
\end{table}



\paragraph{PFOMT}

\paragraph{SOMT}


%\subsection{\Glsentryfirstplural{cmt}}
\subsection{Other \glsentryfirstplural{mt}}
\paragraph{CMTs, NMTs, SMTs}
\paragraph{halogen MTs}
\paragraph{radical chemistry}

\section{Activated methyl cycle?}

\section{\Glsentryfirstplural{mt} in biocatalysis}

The ``methyl effect''.

\subsection{\Glsentryfirstplural{pmt}}
\subsection{\Glsentryfirstplural{dmt}}
\subsection{\Glsentryfirstplural{smmt}}
%\subsection{Terpene synthases and elongases}
%\subsection{Methyl transferases}
%\subsection{Glycosyl transferases}


\section{Motivation}
