%%%-------------------------------------------------%%%
%%% Sub document for Evaluation of PFOMT towards homologous alkylation %%%
%%%-------------------------------------------------%%%

\chapter{Evaluation of PFOMT towards the acceptance of long-chain SAM analogues}

\section{Introduction}

Small changes to molecules can have profound influences on their chemical, physical and biological properties.
Butyric acid esters differing only by a few methylene groups already exhibit quite divergent smells. 
However, not only the macroscopically qualitative properties can differ.
The quantifyable psychotomimetic effect of methylated and ethylated lysergic acid amids differ by at least an order of magnitude \citep{Shulgin1997,Hofmann2000}.
There are many more of these so-called \glspl{sar} and \glspl{qsar} studies on any number of compounds and situations \citep{Santos2014,Alexander1966,Mani1991}. \\
Methylation reactions are one of the key tailoring steps during natural product biosynthesis and can in consequence greatly affect a molecules bio- and physicochemical behavoir \citep{Struck2012,Ley2005}.
However, between the highly complex core structures of natural products, which are produced by a plethora of enzymes (e.g. \glspl{pks}, \glspl{nrps}, terpene cyclases), and the rather simple alkyl-modification introduced by methylation nature is missing some medium-sized modifaction options, that proceed as elegantly as the methylation by \glspl{mt}.
Thus, natural products containing longer chain alkyl modifications like ethyl or propyl moieties on O, N or S-centers have rarely, if ever been observed.\footnote{Reaxys searches for natural product isolates with a molecular mass between (150 and 1500) containing the substructures methyl, ethyl or propyl connected to a heteroatom return 66759, 2797 and 52 results respectively. However, it stands to note that 70\,\% of the propyl results were either esters or otherwise activated moieties. \citep{Elsevier}}


It has recently been shown however, that a wide array of \gls{sam} analogues are used as co-substrates by a variety of \glspl{mt} \citep{Struck2012}.  
The majority of the work so far has been done on \glspl{pmt} and \glspl{dmt} (\autoref{fig:d_lit_sam}), since epi-genetics and finding regions of gene-reulation is of great interest. 
There have been a great many of \gls{sam} analogues synthesized, both chemically and with the help of enzymes \citep{Dalhoff2006,Singh2014}.\\  

\framedfigure[label = fig:d_lit_sam]{%
<<litSAM, echo=F, tidy=TRUE, fig.height=5, fig.width=5, out.width='0.7\\textwidth', dev='pdf', error=T>>=
@ 
}{%
    Graphical representation of the work that has been done on \glspl{mt} in combination with \gls{sam} analogues.
    The grey areas represent individual groups of \gls{sam} analogues (aliphatic, allylic, propargylic, aromatic, \gls{seam} analogues, nitrogen analogues and miscelaneous others). 
    The height of the grey areas represents the number of times a member of the corresponding group has been described as tested in the \gls{mt} literature.
    The height of the colored bars represents the times that individual substrate has been tested. The colors represent the different types of \gls{mt} (red -- \gls{dmt}, green -- \gls{pmt}, lilac -- small molecule \gls{mt}, blue -- \gls{rna} \gls{mt}).
    The black dash across the bar shows the number of times this substrate was actually converted by either enzyme.%    
    }

However, the first description of novel synthetic \gls{sam} analogues with extended carbon chains, including \gls{sae}, allyl and propargyl derivatives, that were also shown to be useful in modifying \gls{dna} via the action of several \glspl{dmt} was provided by Dalhoff, \etal \citep{Dalhoff2006,Dalhoff2006a}. 
It was also noted, that allyl transalkylation reactions proceeded much faster than ethyl- or propyl transfers possibly due to conjugative stabilization of the transition state \citep{Dalhoff2006}.
A whole variety of allyl derivatives was examined by different researchers and site-specific introductions of allyl, pent-2-en-4-ynyl and even 4-propargyloxy-but-2-enyl moieties into proteins (i.e. histones) was demonstrated using \glspl{pmt} \citep{Wang2011,Peters2010}.
However, the larger substrate analogues were not neccesarily accomodated by the native \glspl{pmt} making engineering efforts for the accomodation of larger substrates inevitable \cite{Wang2011}.
The specific introduction of alkine functionalized groups made it then possible to use click chemistry for further functionalization and/or detection of the labelled proteins, DNA or RNA and has been studied extensively (\autoref{fig:d_cuaac}) \citep{Wang2011,Peters2010, Motorin2011, Willnow2012,Schulz2013}.\\ 
In 2012 Bothwell and Luo even described the exchange of the sulfonium with a selenonium center, which afforded \gls{seam} analogues that have since then been described as substrates for several \glspl{pmt} \citep{Bothwell2012,Bothwell2014}.
\gls{seam} analogues have the advantage of being more resistant to chemical decomposition than their sulfur counterparts, but also show enhanced transmethylation reactivity \citep{Bothwell2014}.

\framedfigure[label = fig:d_cuaac]{%
Platzhalter -- Bild Click Chemistry labelling.
}{%
   Labelling of alkynylated macromolecules by \gls{cuaac}.%    
    }
  
There have also been some reports on the use of \gls{sam} analogues by small molecule \glspl{mt}.
In 2009 Stecher \etal reported the use of the \glspl{cmt} NovO and CouO along with synthetic \gls{sam} analogues to accomplish biocatalytic Friedel-Crafts alkyations of some aminocoumarine antibiotics \citep{Stecher2009}.
Lee \etal were the first ones to describe the transfer of a keto-group from an \gls{sam} derivative by means of the small molecule \glspl{mt} catechol \textit{O}-methyl transferase (EC 2.1.1.6) and thiopurine \textit{S}-methyl transferase (EC 2.1.1.67) \citep{Lee2010}.
Furthermore there was work done on the \glspl{omt} RebM and RapM, which modify the antitumor active natural products rebeccamycin and rapamycin respectively, that shows the general feasability of using \gls{sam} analogues in combination with \glspl{mt} to modify small molecules \cite{Law2015,Singh2014,Zhang2006}.
In all of these reports the specificity of the group transfer is retained despite the fact that \gls{sam} analogues are employed as substrates. \\
There is of yet no bioactivity data reported that shows the biological activity of the newly produced compounds.

\gls{pfomt} is highly promiscuous towards its flavonoid substrate \citep{Kopycki2008b,Ibdah2003}.
However, the promiscuity towards different \gls{sam} analogues has net yet been described.
Combination of both, substrate and co-substrate promiscuity in the small molucule \gls{mt} \gls{pfomt} could provide a powerful tool towards the biosynthestic production of novel small molecules with potentially new and promising biological activities.
It was thus of interest, whether or not \gls{pfomt} would accept \gls{sam} analogues as alkyl donors.
The already extensively studied \gls{pfomt} was the prime candidate, since the preparation and crystallizability were established and lots of substrates had already been described \citep{Vogt2004,Ibdah2003,Kopycki2008b,Brandt2015}.


\section{Substrate binding studies using \glsentrytext{itc}}

The binding of different substrates by \gls{pfomt} was examined by \gls{itc}.
\gls{sah}, \gls{sam} and \gls{sae} were selected to study the influence of the alkyl chain length on binding.
Furthermore the binding of the substrate caffeic acid and the influence of \cf{Mg^2+} addition on substrate binding was investigated.

\framedfigure[label = fig:d_itc_substances]{%
Platzhalter -- Untersuchte Substanzen ITC
}{%
   The binding of %    
    }

\section{Determination of the structure of \emph{apo}-\glsentrytext{pfomt}}
\subsection{\glsentrytext{pfomt} activity in \glsentryfirst{des} / Solubility-enhancing effects of \glsentrytext{des}}
vielleicht eigenes kapitel DES?

\section{Study of variants for long-chain alkylations}
\subsection{\glsentrytext{pfomt}-Paper (DIM)}
\subsection{Dockings???}

\section{Conclusion/Discussion}



