%%%-------------------------------------------------%%%
%%% Sub document for appendix %%%
%%%-------------------------------------------------%%%

\part{Appendix}

{\setlength\tabcolsep{1.5pt}

%% \begin{sidewaystable}\caption{Key ions in the positive \gls{esi}-MS\textsuperscript{2} spectra of the flavonoids \molref{naringenin}--\molref{isorhamnetin} using \gls{cid} at \SI{45}{\percent} \gls{nce}.}\centering{\tiny
%% \label{tab:x_CIDfrag}
%%     \begin{tabular}{ll|ccccc|ccccc|ccccc}
%%   \toprule
%% & fragment & \molnum{naringenin} & \molnum{ed} & \molnum{ponciretin} & \molnum{hesperetin} & \molnum{hed} & \molnum{apigenin} & \molnum{luteolin} & \molnum{acacetin} & \molnum{diosmetin} & \molnum{chrysoeriol} & \molnum{kaempferol} & \molnum{quercetin} & \molnum{myricetin} & \molnum{kaempferide} & \molnum{isorhamnetin} \\
%%   %& \begin{sideways} fragment \end{sideways} & \begin{sideways} naringenin \end{sideways} & \begin{sideways} eriodictyol \end{sideways} & \begin{sideways} ponciretin \end{sideways} & \begin{sideways} hesperetin \end{sideways} & \begin{sideways} homoeriodictyol \end{sideways} & \begin{sideways} apigenin \end{sideways} & \begin{sideways} luteolin \end{sideways} & \begin{sideways} acacetin \end{sideways} & \begin{sideways} diosmetin \end{sideways} & \begin{sideways} chrysoeriol \end{sideways} & \begin{sideways} kaempferol \end{sideways} & \begin{sideways} quercetin \end{sideways} & \begin{sideways} myricetin \end{sideways} & \begin{sideways} kaempferide \end{sideways} & \begin{sideways} isorhamnetin \end{sideways} \\ 
%%   \midrule
%% 1 & $\mathrm{[M{+}H]^+}$ &  &  &  &  &  & 271\,(2) &  &  &  &  &  &  &  &  &  \\ 
%%   2 & $\mathrm{[M{+}H{-}CH_{3}]^{\bullet+}}$ &  &  &  &  &  &  &  & 270\,(100) & 286\,(100) & 286\,(100) &  &  &  & 286\,(62) & 302\,(100) \\ 
%%   3 & $\mathrm{[M{+}H{-}CH_{4}]^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 285\,(2) &  \\ 
%%   4 & $\mathrm{[M{+}H{-}H_{2}O]^+}$ & 255\,(1) & 271\,(18) & 269\,(1) & 285\,(10) & 285\,(4) & 253\,(1) & 269\,(9) &  &  &  & 269\,(32) & 285\,(63) & 301\,(40) & 283\,(2) & 299\,(3) \\ 
%%   5 & $\mathrm{[M{+}H{-}CO]^+}$ &  &  &  &  &  & 243\,(7) & 259\,(9) &  &  &  & 259\,(24) & 275\,(14) & 291\,(6) & 273\,(3) &  \\ 
%%   6 & $\mathrm{[M{+}H{-}CHO]^{\bullet+}}$ &  &  &  &  &  & 242\,(14) & 258\,(47) &  &  &  & 258\,(46) & 274\,(20) & 290\,(22) & 272\,(20) & 288\,(3) \\ 
%%   7 & $\mathrm{[M{+}H{-}CH_{3}OH]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 269\,(11) & 285\,(36) \\ 
%%   8 & $\mathrm{[M{+}H{-}2H_{2}O]^+}$ &  & 253\,(4) &  &  &  &  &  &  &  &  &  &  & 283\,(4) &  &  \\ 
%%   9 & $\mathrm{[M{+}H{-}C_{2}H_{2}O]^+}$ & 231\,(4) & 247\,(3) & 245\,(3) & 261\,(2) & 261\,(2) & 229\,(21) & 245\,(13) & 243\,(1) &  &  & 245\,(4) &  &  &  &  \\ 
%%   10 & $\mathrm{[M{+}H{-}CH_{3}{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  & 242\,(7) &  &  &  &  &  & 258\,(9) & 274\,(5) \\ 
%%   11 & $\mathrm{[M{+}H{-}CO_{2}]^+}$ &  &  &  &  &  &  &  &  &  &  & 243\,(5) &  &  &  &  \\ 
%%   12 & $\mathrm{[M{+}H{-}CH_{4}{-}CO]^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 257\,(3) &  \\ 
%%   13 & $\mathrm{[M{+}H{-}H_{2}O{-}CO]^+}$ &  &  &  &  &  & 225\,(13) & 241\,(13) &  &  &  & 241\,(99) & 257\,(100) & 273\,(100) & 255\,(3) & 271\,(5) \\ 
%%   14 & $\mathrm{[M{+}H{-}2CO]^+}$ &  &  &  &  &  &  & 231\,(2) &  &  &  & 231\,(40) & 247\,(37) & 263\,(25) & 245\,(17) & 261\,(8) \\ 
%%   15 & $\mathrm{[M{+}H{-}CH_{3}OH{-}CO]^{\bullet+}}$ &  &  &  &  &  &  & 227\,(3) &  &  &  &  &  &  & 241\,(16) & 257\,(8) \\ 
%%   16 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO]^+}$ &  &  &  &  &  &  & 213\,(2) &  &  &  & 213\,(77) & 229\,(70) & 245\,(32) & 227\,(2) & 243\,(2) \\ 
%%   17 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O]^+}$ & 189\,(5) & 205\,(3) & 203\,(4) & 219\,(2) & 219\,(1) & 187\,(3) & 203\,(4) &  &  &  & 203\,(7) & 219\,(4) & 235\,(4) & 217\,(2) &  \\ 
%%   18 & $\mathrm{[M{+}H{-}CH_{3}OH{-}2CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  & 199\,(3) & 215\,(2) & 231\,(2) & 213\,(4) & 229\,(3) \\ 
%%   19 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O{-}H_{2}O]^+}$ &  & 187\,(4) &  & 201\,(1) &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   20 & $\mathrm{[M{+}H{-}2CO{-}2C_{2}H_{2}O]^+}$ &  &  &  &  &  &  &  &  &  &  & 147\,(13) & 163\,(7) & 179\,(7) & 161\,(13) & 177\,(2) \\ 
%%   21 & $\mathrm{AC^+}$ & 179\,(4) & 179\,(20) & 179\,(5) & 179\,(28) & 179\,(30) &  &  &  &  &  &  & 191\,(1) &  &  &  \\ 
%%   22 & $\mathrm{0{,}2A^+}$ &  &  &  &  &  &  &  &  &  &  & 165\,(100) & 165\,(59) & 165\,(41) & 165\,(31) & 165\,(6) \\ 
%%   23 & $\mathrm{0{,}2A^+{-}CO}$ &  &  &  &  &  &  &  &  &  &  & 137\,(11) & 137\,(23) & 137\,(6) & 137\,(4) &  \\ 
%%   24 & $\mathrm{0{,}2B^+}$ &  &  &  &  &  & 121\,(6) & 137\,(7) &  &  &  & 121\,(36) & 137\,(23) & 153\,(35) & 135\,(18) & 151\,(2) \\ 
%%   25 & $\mathrm{0{,}3A^+}$ &  &  &  &  &  &  & 137\,(7) &  &  &  & 137\,(11) & 137\,(23) & 137\,(6) & 137\,(4) &  \\ 
%%   26 & $\mathrm{0{,}3A^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 139\,(100) & 139\,(9) \\ 
%%   27 & $\mathrm{0{,}4A^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 111\,(1) &  \\ 
%%   28 & $\mathrm{0{,}4B^+}$ &  &  &  &  &  & 163\,(6) & 179\,(7) &  &  &  &  &  &  &  &  \\ 
%%   29 & $\mathrm{0{,}4B^+{-}H_{2}O}$ &  &  &  &  &  & 145\,(13) &  &  &  &  &  &  &  &  &  \\ 
%%   30 & $\mathrm{1{,}3A^+}$ & 153\,(100) & 153\,(31) & 153\,(77) & 153\,(21) & 153\,(57) & 153\,(100) & 153\,(100) & 153\,(5) &  &  & 153\,(61) & 153\,(20) & 153\,(35) & 153\,(28) & 153\,(4) \\ 
%%   31 & $\mathrm{1{,}3A^+{-}C_{2}H_{2}O}$ &  &  &  &  &  &  &  &  &  &  & 111\,(19) & 111\,(7) & 111\,(4) &  &  \\ 
%%   32 & $\mathrm{1{,}3B^+}$ &  &  &  &  &  & 119\,(12) & 135\,(11) & 133\,(2) &  &  &  &  &  &  &  \\ 
%%   33 & $\mathrm{1{,}3B^+{-}2H}$ &  &  &  &  &  &  &  &  &  &  & 133\,(25) & 149\,(10) & 165\,(41) &  & 163\,(2) \\ 
%%   34 & $\mathrm{1{,}4A^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  & 127\,(2) & 127\,(1) & 127\,(4) &  &  \\ 
%%   35 & $\mathrm{1{,}4B^+{-}2H}$ & 147\,(84) & 163\,(100) & 161\,(100) & 177\,(100) & 177\,(100) &  &  &  &  &  &  &  &  &  &  \\ 
%%   36 & $\mathrm{1{,}4B^+{+}2H{-}H_{2}O}$ &  &  &  &  &  &  &  &  &  &  & 147\,(13) &  &  & 161\,(13) &  \\ 
%%   37 & $\mathrm{1{,}4B^+{-}2H{-}H_{2}O}$ &  & 145\,(5) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   38 & $\mathrm{1{,}4B^+{-}2H{-}CO}$ & 119\,(3) & 135\,(1) & 133\,(4) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   39 & $\mathrm{C_{7}H_{7}^+}$ &  &  &  &  &  & 91\,(1) &  &  &  &  &  &  &  &  &  \\ 
%%    \bottomrule
%% \end{tabular}
%% }
%% \end{sidewaystable}

%% \begin{sidewaystable}\caption{Key ions in the positive \gls{esi}-MS\textsuperscript{2} spectra of the flavonoids \molref{naringenin}--\molref{isorhamnetin} using \gls{hcd} at \SI{75}{\percent} \gls{nce}.}\centering{\tiny
%% \label{tab:x_HCD75frag}
%%     \begin{tabular}{ll|ccccc|ccccc|ccccc}
%%   \toprule
%% & fragment & \molref*{naringenin} & \molref*{ed} & \molref*{ponciretin} & \molref*{hesperetin} & \molref*{hed} & \molref*{apigenin} & \molref*{luteolin} & \molref*{acacetin} & \molref*{diosmetin} & \molref*{chrysoeriol} & \molref*{kaempferol} & \molref*{quercetin} & \molref*{myricetin} & \molref*{kaempferide} & \molref*{isorhamnetin} \\
%%   %  & \begin{sideways} fragment \end{sideways} & \begin{sideways} naringenin \end{sideways} & \begin{sideways} eriodictyol \end{sideways} & \begin{sideways} ponciretin \end{sideways} & \begin{sideways} hesperetin \end{sideways} & \begin{sideways} homoeriodictyol \end{sideways} & \begin{sideways} apigenin \end{sideways} & \begin{sideways} luteolin \end{sideways} & \begin{sideways} acacetin \end{sideways} & \begin{sideways} diosmetin \end{sideways} & \begin{sideways} chrysoeriol \end{sideways} & \begin{sideways} kaempferol \end{sideways} & \begin{sideways} quercetin \end{sideways} & \begin{sideways} myricetin \end{sideways} & \begin{sideways} kaempferide \end{sideways} & \begin{sideways} isorhamnetin \end{sideways} \\ 
%%   \midrule
%% 1 & $\mathrm{[M{+}H]^+}$ &  &  &  &  &  & 271\,(84) & 287\,(66) & 285\,(4) &  &  & 287\,(25) & 303\,(8) & 319\,(1) & 301\,(9) &  \\ 
%%   2 & $\mathrm{[M{+}H{-}CH_{3}]^{\bullet+}}$ &  &  &  &  &  &  &  & 270\,(9) & 286\,(20) & 286\,(18) &  &  &  & 286\,(12) & 302\,(6) \\ 
%%   3 & $\mathrm{[M{+}H{-}CH_{4}]^+}$ &  &  &  & 287\,(1) &  &  &  &  &  &  &  &  &  & 285\,(5) & 301\,(3) \\ 
%%   4 & $\mathrm{[M{+}H{-}H_{2}O]^+}$ &  &  &  &  &  & 253\,(3) & 269\,(6) &  &  &  & 269\,(2) & 285\,(6) & 301\,(1) &  &  \\ 
%%   5 & $\mathrm{[M{+}H{-}CO]^+}$ &  &  &  &  &  & 243\,(7) &  &  &  &  & 259\,(3) &  &  &  &  \\ 
%%   6 & $\mathrm{[M{+}H{-}CHO]^{\bullet+}}$ &  &  &  &  &  & 242\,(1) & 258\,(3) &  &  &  & 258\,(10) & 274\,(4) &  & 272\,(2) &  \\ 
%%   7 & $\mathrm{[M{+}H{-}CH_{3}OH]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 269\,(11) & 285\,(11) \\ 
%%   8 & $\mathrm{[M{+}H{-}C_{2}H_{2}O]^+}$ &  &  &  &  &  & 229\,(4) &  &  &  &  &  &  &  &  &  \\ 
%%   9 & $\mathrm{[M{+}H{-}CH_{3}{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  & 242\,(100) & 258\,(100) & 258\,(100) &  &  &  & 258\,(58) & 274\,(6) \\ 
%%   10 & $\mathrm{[M{+}H{-}CH_{4}{-}CO]^+}$ &  &  &  &  &  &  &  & 241\,(1) & 257\,(7) & 257\,(7) &  &  &  & 257\,(17) & 273\,(13) \\ 
%%   11 & $\mathrm{[M{+}H{-}H_{2}O{-}CO]^+}$ &  &  &  &  &  & 225\,(4) & 241\,(16) &  &  &  & 241\,(5) & 257\,(13) & 273\,(6) &  &  \\ 
%%   12 & $\mathrm{[M{+}H{-}2CO]^+}$ &  &  &  &  &  &  &  &  &  &  & 231\,(5) & 247\,(2) &  &  &  \\ 
%%   13 & $\mathrm{[M{+}H{-}CH_{3}OH{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 241\,(2) & 257\,(7) \\ 
%%   14 & $\mathrm{[M{+}H{-}CH_{3}{-}H_{2}O{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 240\,(2) & 256\,(2) \\ 
%%   15 & $\mathrm{[M{+}H{-}CH_{3}{-}2CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  & 216\,(2) & 232\,(2) &  & 230\,(94) & 246\,(9) \\ 
%%   16 & $\mathrm{[M{+}H{-}H_{2}O{-}CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  & 229\,(12) & 229\,(13) &  &  &  & 229\,(100) & 245\,(42) \\ 
%%   17 & $\mathrm{[M{+}H{-}CH_{4}{-}2CO]^+}$ &  &  &  &  &  &  &  &  & 229\,(12) & 229\,(13) &  &  &  & 229\,(100) & 245\,(42) \\ 
%%   18 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO]^+}$ &  &  &  &  &  & 197\,(4) & 213\,(7) &  &  &  & 213\,(20) & 229\,(49) & 245\,(22) & 227\,(2) &  \\ 
%%   19 & $\mathrm{[M{+}H{-}3CO]^+}$ &  &  &  &  &  &  &  &  &  &  & 203\,(2) &  & 235\,(2) &  &  \\ 
%%   20 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O]^+}$ &  &  &  &  &  & 187\,(2) & 203\,(2) &  &  &  &  & 219\,(1) &  &  &  \\ 
%%   21 & $\mathrm{[M{+}H{-}CH_{3}OH{-}2CO]^{\bullet+}}$ &  &  &  &  &  &  & 199\,(1) &  &  &  &  &  & 231\,(1) & 213\,(11) & 229\,(33) \\ 
%%   22 & $\mathrm{[M{+}H{-}H_{2}O{-}CO{-}2C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 203\,(3) & 219\,(7) \\ 
%%   23 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  &  &  &  & 203\,(3) & 219\,(8) & 201\,(25) & 217\,(41) \\ 
%%   24 & $\mathrm{[M{+}H{-}CH_{4}{-}3CO]^+}$ &  &  &  &  &  &  &  &  &  &  &  & 203\,(3) & 219\,(8) & 201\,(25) & 217\,(41) \\ 
%%   25 & $\mathrm{[M{+}H{-}CH_{4}{-}2CO{-}C_{2}H_{2}O]^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 187\,(4) & 203\,(18) \\ 
%%   26 & $\mathrm{[M{+}H{-}2CO{-}2C_{2}H_{2}O]^+}$ &  &  &  &  &  & 131\,(2) & 147\,(1) &  &  &  & 147\,(9) & 163\,(7) & 179\,(9) & 161\,(4) &  \\ 
%%   27 & $\mathrm{AC^+}$ &  & 179\,(1) &  & 179\,(2) & 179\,(2) &  &  &  &  &  &  & 191\,(2) & 191\,(2) &  & 191\,(1) \\ 
%%   28 & $\mathrm{0{,}2A^+}$ &  &  &  &  &  &  &  &  &  &  & 165\,(11) & 165\,(9) & 165\,(6) & 165\,(6) & 165\,(1) \\ 
%%   29 & $\mathrm{0{,}2A^+{-}CO}$ &  &  &  &  &  &  &  &  &  &  & 137\,(14) & 137\,(47) & 137\,(15) & 137\,(7) & 137\,(4) \\ 
%%   30 & $\mathrm{0{,}2B^+}$ &  &  &  &  &  & 121\,(16) & 137\,(12) &  &  &  &  & 137\,(47) & 153\,(100) & 135\,(14) & 151\,(2) \\ 
%%   31 & $\mathrm{0{,}3A^+}$ &  &  &  &  &  &  & 137\,(12) &  &  &  & 137\,(14) & 137\,(47) & 137\,(15) & 137\,(7) & 137\,(4) \\ 
%%   32 & $\mathrm{0{,}3A^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  &  &  & 139\,(3) & 139\,(7) & 139\,(1) \\ 
%%   33 & $\mathrm{0{,}4A^+{+}2H}$ &  &  &  &  & 111\,(2) &  &  &  &  &  &  &  &  &  &  \\ 
%%   34 & $\mathrm{0{,}4B^+}$ &  &  &  &  &  & 163\,(8) & 179\,(3) &  &  &  &  &  &  &  &  \\ 
%%   35 & $\mathrm{0{,}4B^+{-}H_{2}O}$ &  &  &  &  &  & 145\,(17) & 161\,(16) &  &  &  &  &  &  &  &  \\ 
%%   36 & $\mathrm{1{,}3A^+}$ & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(11) & 153\,(8) & 153\,(8) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(65) & 153\,(100) \\ 
%%   37 & $\mathrm{1{,}3A^+{-}CO}$ &  &  &  &  &  & 125\,(1) & 125\,(2) &  &  &  &  &  & 125\,(3) &  &  \\ 
%%   38 & $\mathrm{1{,}3A^+{-}C_{2}H_{2}O}$ &  & 111\,(2) & 111\,(1) & 111\,(1) &  & 111\,(2) & 111\,(2) &  &  &  & 111\,(5) & 111\,(6) & 111\,(6) & 111\,(1) &  \\ 
%%   39 & $\mathrm{1{,}3A^+{-}2CO}$ & 97\,(3) & 97\,(4) & 97\,(3) & 97\,(4) & 97\,(4) & 97\,(2) & 97\,(2) &  &  &  & 97\,(2) & 97\,(2) & 97\,(3) &  &  \\ 
%%   40 & $\mathrm{1{,}3A^+{-}2CO{-}C_{2}H_{4}}$ & 69\,(2) & 69\,(2) & 69\,(2) & 69\,(2) & 69\,(2) & 69\,(4) & 69\,(5) &  &  &  & 69\,(7) & 69\,(8) & 69\,(8) & 69\,(3) & 69\,(1) \\ 
%%   41 & $\mathrm{1{,}3B^+}$ &  &  &  &  &  & 119\,(49) & 135\,(40) & 133\,(3) &  &  &  &  &  &  &  \\ 
%%   42 & $\mathrm{1{,}3B^+{-}2H}$ &  &  &  &  &  &  &  &  &  &  & 133\,(3) & 149\,(3) & 165\,(6) &  & 163\,(1) \\ 
%%   43 & $\mathrm{1{,}4A^+{+}2H}$ &  &  &  &  &  &  & 127\,(1) &  &  &  & 127\,(1) & 127\,(3) & 127\,(2) &  &  \\ 
%%   44 & $\mathrm{1{,}4A^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  & 124\,(2) & 124\,(11) & 124\,(3) \\ 
%%   45 & $\mathrm{1{,}4A^+}$ &  &  &  &  &  & 125\,(1) & 125\,(2) &  &  &  &  &  & 125\,(3) &  &  \\ 
%%   46 & $\mathrm{1{,}4B^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  &  & 145\,(2) & 161\,(2) &  &  \\ 
%%   47 & $\mathrm{1{,}4B^+{-}2H}$ & 147\,(15) & 163\,(10) & 161\,(10) & 177\,(4) & 177\,(2) &  &  &  &  &  &  &  &  &  &  \\ 
%%   48 & $\mathrm{1{,}4B^+{+}2H{-}H_{2}O}$ &  &  &  &  &  &  &  &  &  &  & 147\,(9) &  &  & 161\,(4) &  \\ 
%%   49 & $\mathrm{1{,}4B^+{-}2H{-}H_{2}O}$ &  & 145\,(7) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   50 & $\mathrm{1{,}4B^+{-}2H{-}CO}$ & 119\,(32) & 135\,(29) & 133\,(36) & 149\,(15) & 149\,(11) &  &  &  &  &  &  &  &  &  &  \\ 
%%   51 & $\mathrm{1{,}4B^+{-}2H{-}CO{-}CH_{3}}$ &  &  & 118\,(11) & 134\,(11) & 134\,(7) &  &  &  &  &  &  &  &  &  &  \\ 
%%   52 & $\mathrm{1{,}4B^+{-}2H{-}CO{-}CH_{2}O}$ &  &  & 103\,(6) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   53 & $\mathrm{1{,}4B^+{-}2H{-}2CO}$ & 91\,(24) &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   54 & $\mathrm{1{,}4B^+{-}2H{-}2CO{-}CH_{3}}$ &  &  & 90\,(3) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   55 & $\mathrm{1{,}4B^+{-}2H{-}C_{2}H_{2}O{-}H_{2}O}$ &  &  &  & 117\,(15) & 117\,(32) &  &  &  &  &  &  &  &  &  &  \\ 
%%   56 & $\mathrm{1{,}4B^+{-}2H{-}H_{2}O{-}CO}$ &  & 117\,(18) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   57 & $\mathrm{C_{7}H_{6}O_{5}^+}$ &  &  &  &  &  &  &  &  &  &  &  &  & 170\,(1) & 170\,(10) & 170\,(2) \\ 
%%   58 & $\mathrm{C_{7}H_{7}^+}$ & 91\,(24) &  & 91\,(1) & 91\,(3) & 91\,(2) & 91\,(26) &  &  &  &  & 91\,(2) & 91\,(2) & 91\,(2) & 91\,(4) &  \\ 
%%   59 & $\mathrm{C_{7}H_{5}^+}$ &  & 89\,(23) &  & 89\,(29) & 89\,(24) &  & 89\,(17) &  &  &  &  &  &  &  &  \\ 
%%   60 & $\mathrm{C_{5}H_{5}O^+}$ &  &  &  &  &  & 81\,(1) & 81\,(2) &  &  &  & 81\,(3) & 81\,(8) & 81\,(5) & 81\,(1) & 81\,(1) \\ 
%%    \bottomrule
%% \end{tabular}
%% }
%%\end{sidewaystable}


%% \begin{sidewaystable}\caption{Key ions in the positive \gls{esi}-MS\textsuperscript{2} spectra of the flavonoids \molref{naringenin}--\molref{isorhamnetin} using \gls{hcd} at \SI{100}{\percent} \gls{nce}.}\centering{\tiny
%% \label{tab:x_HCD100frag}
%%     \begin{tabular}{ll|ccccc|ccccc|ccccc}
%%   \toprule
%% & fragment & \molref*{naringenin} & \molref*{ed} & \molref*{ponciretin} & \molref*{hesperetin} & \molref*{hed} & \molref*{apigenin} & \molref*{luteolin} & \molref*{acacetin} & \molref*{diosmetin} & \molref*{chrysoeriol} & \molref*{kaempferol} & \molref*{quercetin} & \molref*{myricetin} & \molref*{kaempferide} & \molref*{isorhamnetin} \\
%%   % & \begin{sideways} fragment \end{sideways} & \begin{sideways} naringenin \end{sideways} & \begin{sideways} eriodictyol \end{sideways} & \begin{sideways} ponciretin \end{sideways} & \begin{sideways} hesperetin \end{sideways} & \begin{sideways} homoeriodictyol \end{sideways} & \begin{sideways} apigenin \end{sideways} & \begin{sideways} luteolin \end{sideways} & \begin{sideways} acacetin \end{sideways} & \begin{sideways} diosmetin \end{sideways} & \begin{sideways} chrysoeriol \end{sideways} & \begin{sideways} kaempferol \end{sideways} & \begin{sideways} quercetin \end{sideways} & \begin{sideways} myricetin \end{sideways} & \begin{sideways} kaempferide \end{sideways} & \begin{sideways} isorhamnetin \end{sideways} \\ 
%%   \midrule
%% 1 & $\mathrm{[M{+}H]^+}$ &  &  &  &  &  & 271\,(2) & 287\,(2) &  &  &  &  &  &  &  &  \\ 
%%   2 & $\mathrm{[M{+}H{-}CH_{4}]^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 285\,(1) &  \\ 
%%   3 & $\mathrm{[M{+}H{-}H_{2}O]^+}$ &  &  &  &  &  &  &  &  &  &  & 269\,(2) & 285\,(3) &  &  &  \\ 
%%   4 & $\mathrm{[M{+}H{-}CO]^+}$ &  &  &  &  &  & 243\,(2) &  &  &  &  &  &  &  &  &  \\ 
%%   5 & $\mathrm{[M{+}H{-}CHO]^{\bullet+}}$ &  &  &  &  &  & 242\,(2) & 258\,(2) &  &  &  &  &  &  &  &  \\ 
%%   6 & $\mathrm{[M{+}H{-}CH_{3}OH]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 269\,(3) & 285\,(3) \\ 
%%   7 & $\mathrm{[M{+}H{-}CH_{3}{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  & 242\,(49) & 258\,(49) & 258\,(46) &  &  &  & 258\,(2) &  \\ 
%%   8 & $\mathrm{[M{+}H{-}CH_{4}{-}CO]^+}$ &  &  &  &  &  &  &  & 241\,(7) & 257\,(38) & 257\,(37) &  &  &  & 257\,(6) & 273\,(2) \\ 
%%   9 & $\mathrm{[M{+}H{-}H_{2}O{-}CO]^+}$ &  &  &  &  &  &  & 241\,(4) &  &  &  & 241\,(1) & 257\,(2) &  &  &  \\ 
%%   10 & $\mathrm{[M{+}H{-}CH_{3}OH{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  &  &  & 257\,(2) \\ 
%%   11 & $\mathrm{[M{+}H{-}CH_{3}{-}2CO]^{\bullet+}}$ &  &  &  &  &  &  & 216\,(1) &  &  &  & 216\,(2) &  &  & 230\,(9) &  \\ 
%%   12 & $\mathrm{[M{+}H{-}H_{2}O{-}CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  & 213\,(6) & 229\,(75) & 229\,(76) &  &  &  & 229\,(100) & 245\,(34) \\ 
%%   13 & $\mathrm{[M{+}H{-}CH_{4}{-}2CO]^+}$ &  &  &  &  &  &  &  & 213\,(6) & 229\,(75) & 229\,(76) &  &  &  & 229\,(100) & 245\,(34) \\ 
%%   14 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO]^+}$ &  &  &  &  &  & 197\,(3) & 213\,(4) &  &  &  & 213\,(12) & 229\,(16) & 245\,(6) &  &  \\ 
%%   15 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O]^+}$ &  &  &  &  &  & 187\,(1) & 203\,(3) &  &  &  & 203\,(1) & 219\,(2) &  &  &  \\ 
%%   16 & $\mathrm{[M{+}H{-}CH_{3}OH{-}2CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  & 213\,(4) & 213\,(4) &  &  &  & 213\,(10) & 229\,(15) \\ 
%%   17 & $\mathrm{[M{+}H{-}H_{2}O{-}CO{-}2C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  & 203\,(29) & 203\,(31) &  &  &  & 203\,(11) & 219\,(13) \\ 
%%   18 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  & 187\,(2) & 185\,(1) & 201\,(7) & 201\,(6) & 187\,(2) & 203\,(10) & 219\,(21) & 201\,(50) & 217\,(56) \\ 
%%   19 & $\mathrm{[M{+}H{-}CH_{4}{-}3CO]^+}$ &  &  &  &  &  &  & 187\,(2) & 185\,(1) & 201\,(7) & 201\,(6) & 187\,(2) & 203\,(10) & 219\,(21) & 201\,(50) & 217\,(56) \\ 
%%   20 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O{-}H_{2}O]^+}$ &  &  &  &  &  & 169\,(2) & 185\,(2) &  &  &  &  &  &  &  &  \\ 
%%   21 & $\mathrm{[M{+}H{-}CH_{4}{-}2CO{-}C_{2}H_{2}O]^+}$ &  &  &  &  &  &  &  &  & 187\,(6) & 187\,(5) &  &  &  & 187\,(13) & 203\,(37) \\ 
%%   22 & $\mathrm{[M{+}H{-}2CO{-}2C_{2}H_{2}O]^+}$ &  &  &  &  &  & 131\,(5) & 147\,(3) &  & 161\,(4) & 161\,(5) & 147\,(8) & 163\,(5) & 179\,(9) &  &  \\ 
%%   23 & $\mathrm{AC^+}$ &  &  &  & 179\,(2) & 179\,(1) &  &  &  &  &  &  &  & 191\,(2) &  & 191\,(2) \\ 
%%   24 & $\mathrm{0{,}2A^+}$ &  &  &  &  &  &  &  &  &  &  & 165\,(2) & 165\,(3) & 165\,(4) & 165\,(2) & 165\,(1) \\ 
%%   25 & $\mathrm{0{,}2A^+{-}CO}$ &  &  &  &  &  &  &  &  &  &  & 137\,(12) & 137\,(38) & 137\,(32) & 137\,(8) & 137\,(13) \\ 
%%   26 & $\mathrm{0{,}2B^+}$ &  &  &  &  &  & 121\,(25) & 137\,(16) &  &  &  & 121\,(69) & 137\,(38) & 153\,(100) & 135\,(5) & 151\,(1) \\ 
%%   27 & $\mathrm{0{,}3A^+}$ &  &  &  & 137\,(3) & 137\,(2) &  & 137\,(16) &  & 137\,(1) & 137\,(2) & 137\,(12) & 137\,(38) & 137\,(32) & 137\,(8) & 137\,(13) \\ 
%%   28 & $\mathrm{0{,}3A^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  &  &  & 139\,(3) &  &  \\ 
%%   29 & $\mathrm{0{,}4B^+}$ &  &  &  &  &  & 163\,(2) &  &  &  &  &  &  &  &  &  \\ 
%%   30 & $\mathrm{0{,}4B^+{-}H_{2}O}$ &  &  &  &  &  & 145\,(41) & 161\,(29) &  &  &  &  &  &  &  &  \\ 
%%   31 & $\mathrm{1{,}3A^+}$ & 153\,(69) & 153\,(50) & 153\,(100) & 153\,(63) & 153\,(58) & 153\,(84) & 153\,(87) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(67) & 153\,(100) \\ 
%%   32 & $\mathrm{1{,}3A^+{-}CO}$ & 125\,(1) &  & 125\,(1) & 125\,(1) &  & 125\,(3) & 125\,(2) &  &  &  & 125\,(2) & 125\,(1) & 125\,(5) &  &  \\ 
%%   33 & $\mathrm{1{,}3A^+{-}C_{2}H_{2}O}$ & 111\,(2) & 111\,(2) & 111\,(4) & 111\,(2) & 111\,(2) & 111\,(4) & 111\,(3) &  & 111\,(1) & 111\,(1) & 111\,(4) & 111\,(5) & 111\,(7) & 111\,(3) & 111\,(6) \\ 
%%   34 & $\mathrm{1{,}3A^+{-}2CO}$ & 97\,(10) & 97\,(8) & 97\,(15) & 97\,(9) & 97\,(9) & 97\,(9) & 97\,(9) & 97\,(1) & 97\,(2) & 97\,(2) & 97\,(9) & 97\,(10) & 97\,(14) & 97\,(3) & 97\,(3) \\ 
%%   35 & $\mathrm{1{,}3A^+{-}2CO{-}C_{2}H_{4}}$ & 69\,(9) & 69\,(8) & 69\,(13) & 69\,(9) & 69\,(8) & 69\,(24) & 69\,(22) & 69\,(1) & 69\,(2) & 69\,(2) & 69\,(33) & 69\,(31) & 69\,(29) & 69\,(10) & 69\,(8) \\ 
%%   36 & $\mathrm{1{,}3B^+}$ &  &  &  &  &  & 119\,(35) &  &  &  &  &  &  &  &  &  \\ 
%%   37 & $\mathrm{1{,}3B^+{-}2H}$ &  &  &  &  &  &  &  &  &  &  & 133\,(1) & 149\,(4) & 165\,(4) & 147\,(3) & 163\,(5) \\ 
%%   38 & $\mathrm{1{,}4A^+{+}2H}$ &  &  &  &  &  &  & 127\,(2) &  &  &  & 127\,(2) & 127\,(6) & 127\,(4) &  &  \\ 
%%   39 & $\mathrm{1{,}4A^{\bullet+}}$ &  &  &  &  &  &  & 124\,(2) & 124\,(4) & 124\,(4) & 124\,(5) & 124\,(1) & 124\,(3) & 124\,(15) & 124\,(42) & 124\,(14) \\ 
%%   40 & $\mathrm{1{,}4A^+}$ & 125\,(1) &  & 125\,(1) & 125\,(1) &  & 125\,(3) & 125\,(2) &  &  &  & 125\,(2) & 125\,(1) & 125\,(5) &  &  \\ 
%%   41 & $\mathrm{1{,}4B^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  &  & 145\,(4) & 161\,(4) &  & 159\,(2) \\ 
%%   42 & $\mathrm{1{,}4B^+{-}2H}$ & 147\,(3) & 163\,(1) & 161\,(3) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   43 & $\mathrm{1{,}4B^+{+}2H{-}H_{2}O}$ &  &  &  &  &  &  &  &  &  &  & 147\,(8) &  &  &  &  \\ 
%%   44 & $\mathrm{1{,}4B^+{-}2H{-}H_{2}O}$ &  & 145\,(1) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   45 & $\mathrm{1{,}4B^+{-}2H{-}CO}$ & 119\,(34) & 135\,(16) & 133\,(36) & 149\,(5) & 149\,(3) &  &  &  &  &  &  &  &  &  &  \\ 
%%   46 & $\mathrm{1{,}4B^+{-}2H{-}CO{-}CH_{3}}$ &  &  & 118\,(57) & 134\,(20) & 134\,(13) &  &  &  &  &  &  &  &  &  &  \\ 
%%   47 & $\mathrm{1{,}4B^+{-}2H{-}CO{-}CH_{2}O}$ &  &  & 103\,(27) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   48 & $\mathrm{1{,}4B^+{-}2H{-}2CO}$ & 91\,(100) &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   49 & $\mathrm{1{,}4B^+{-}2H{-}2CO{-}CH_{3}}$ &  &  & 90\,(49) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   50 & $\mathrm{1{,}4B^+{-}2H{-}C_{2}H_{2}O{-}H_{2}O}$ &  &  &  & 117\,(13) & 117\,(26) &  &  &  &  &  &  &  &  &  &  \\ 
%%   51 & $\mathrm{1{,}4B^+{-}2H{-}H_{2}O{-}CO}$ &  & 117\,(21) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%%   52 & $\mathrm{C_{7}H_{6}O_{5}^+}$ &  &  &  &  &  &  &  & 170\,(1) & 170\,(1) & 170\,(1) &  &  & 170\,(3) & 170\,(8) & 170\,(3) \\ 
%%   53 & $\mathrm{C_{7}H_{7}^+}$ & 91\,(100) &  & 91\,(5) & 91\,(7) & 91\,(5) &  &  &  &  &  &  &  &  &  &  \\ 
%%   54 & $\mathrm{C_{7}H_{5}^+}$ &  & 89\,(100) & 89\,(22) & 89\,(100) & 89\,(100) & 89\,(7) & 89\,(100) & 89\,(3) &  & 89\,(1) & 89\,(6) & 89\,(9) & 89\,(7) & 89\,(2) & 89\,(2) \\ 
%%   55 & $\mathrm{C_{5}H_{5}O^+}$ & 81\,(1) & 81\,(1) & 81\,(1) & 81\,(2) & 81\,(1) & 81\,(3) & 81\,(8) &  &  &  & 81\,(12) & 81\,(39) & 81\,(24) & 81\,(4) & 81\,(7) \\ 
%%    \bottomrule
%% \end{tabular}
%% }
%% \end{sidewaystable}


\begin{sidewaystable}\centering\caption{Key ions in the positive mode CID and HCD ESI-MS\tup{2} spectra of flavanones.}
  \label{tab:x_flavanonfrag}{\scriptsize%\tiny
\begin{tabular}{ll|ccccc|ccccc|ccccc}
  \toprule
&  \multirow{2}{*}{fragment} & \multicolumn{5}{c}{\textbf{CID, \SI{45}{\percent} NCE}} & \multicolumn{5}{c}{\textbf{HCD, \SI{75}{\percent} NCE}} & \multicolumn{5}{c}{\textbf{HCD, \SI{100}{\percent} NCE}} \\
%  & & naringenin & eriodictyol & ponciretin & homoeriodictyol & hesperetin & naringenin & eriodictyol & ponciretin & homoeriodictyol & hesperetin & naringenin & eriodictyol & ponciretin & homoeriodictyol & hesperetin \\
  & & (\textbf{1}) & (\textbf{2}) & (\textbf{3}) & (\textbf{4}) & (\textbf{5}) & (\textbf{1}) & (\textbf{2}) & (\textbf{3}) & (\textbf{4}) & (\textbf{5}) & (\textbf{1}) & (\textbf{2}) & (\textbf{3}) & (\textbf{4}) & (\textbf{5}) \\
  % & \begin{sideways} fragment \end{sideways} & \begin{sideways} naringenin\_CID.45 \end{sideways} & \begin{sideways} eriodictyol\_CID.45 \end{sideways} & \begin{sideways} ponciretin\_CID.45 \end{sideways} & \begin{sideways} hesperetin\_CID.45 \end{sideways} & \begin{sideways} homoeriodictyol\_CID.45 \end{sideways} & \begin{sideways} naringenin\_HCD.75 \end{sideways} & \begin{sideways} eriodictyol\_HCD.75 \end{sideways} & \begin{sideways} ponciretin\_HCD.75 \end{sideways} & \begin{sideways} hesperetin\_HCD.75 \end{sideways} & \begin{sideways} homoeriodictyol\_HCD.75 \end{sideways} & \begin{sideways} naringenin\_HCD.100 \end{sideways} & \begin{sideways} eriodictyol\_HCD.100 \end{sideways} & \begin{sideways} ponciretin\_HCD.100 \end{sideways} & \begin{sideways} hesperetin\_HCD.100 \end{sideways} & \begin{sideways} homoeriodictyol\_HCD.100 \end{sideways} \\ 
  \midrule
%1 & $\mathrm{[M{+}H{-}CH_{4}]^+}$ &  &  &  &  &  &  &  &  & 287\,(1) &  &  &  &  &  &  \\ 
  2 & $\mathrm{[M{+}H{-}H_{2}O]^+}$ & 255\,(1) & 271\,(18) & 269\,(1) & 285\,(10) & 285\,(4) &  &  &  &  &  &  &  &  &  &  \\ 
%  3 & $\mathrm{[M{+}H{-}2H_{2}O]^+}$ &  & 253\,(4) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  4 & $\mathrm{[M{+}H{-}C_{2}H_{2}O]^+}$ & 231\,(4) & 247\,(3) & 245\,(3) & 261\,(2) & 261\,(2) &  &  &  &  &  &  &  &  &  &  \\ 
  5 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O]^+}$ & 189\,(5) & 205\,(3) & 203\,(4) & 219\,(2) & 219\,(1) &  &  &  &  &  &  &  &  &  &  \\ 
%  6 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O{-}H_{2}O]^+}$ &  & 187\,(4) &  & 201\,(1) &  &  &  &  &  &  &  &  &  &  &  \\ 
%  7 & $\mathrm{[M{+}H{-}CH_{4}{-}4CO]^+}$ &  & 161\,(2) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  8 & $\mathrm{AC^+}$ & 179\,(4) & 179\,(20) & 179\,(5) & 179\,(28) & 179\,(30) &  & 179\,(1) &  & 179\,(2) & 179\,(2) &  &  &  & 179\,(2) & 179\,(1) \\ 
%  9 & $\mathrm{0{,}3A^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 137\,(3) & 137\,(2) \\ 
%  10 & $\mathrm{0{,}4A^+{+}2H}$ &  &  &  &  &  &  &  &  &  & 111\,(2) &  &  &  &  &  \\ 
  11 & $\mathrm{1{,}3A^+}$ & 153\,(100) & 153\,(31) & 153\,(77) & 153\,(21) & 153\,(57) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(69) & 153\,(50) & 153\,(100) & 153\,(63) & 153\,(58) \\ 
  12 & $\mathrm{1{,}3A^+{-}CO}$ &  &  &  &  &  &  &  &  &  &  & 125\,(1) &  & 125\,(1) & 125\,(1) &  \\ 
  13 & $\mathrm{1{,}3A^+{-}C_{2}H_{2}O}$ &  &  &  &  &  &  & 111\,(2) & 111\,(1) & 111\,(1) &  & 111\,(2) & 111\,(2) & 111\,(4) & 111\,(2) & 111\,(2) \\ 
  14 & $\mathrm{1{,}3A^+{-}2CO}$ &  &  &  &  &  & 97\,(3) & 97\,(4) & 97\,(3) & 97\,(4) & 97\,(4) & 97\,(10) & 97\,(8) & 97\,(15) & 97\,(9) & 97\,(9) \\ 
  15 & $\mathrm{1{,}3A^+{-}2CO{-}C_{2}H_{4}}$ &  &  &  &  &  & 69\,(2) & 69\,(2) & 69\,(2) & 69\,(2) & 69\,(2) & 69\,(9) & 69\,(8) & 69\,(13) & 69\,(9) & 69\,(8) \\ 
 % 16 & $\mathrm{1{,}4A^+}$ &  &  &  &  &  &  &  &  &  &  & 125\,(1) &  & 125\,(1) & 125\,(1) &  \\ 
  17 & $\mathrm{1{,}4B^+{-}2H}$ & 147\,(84) & 163\,(100) & 161\,(100) & 177\,(100) & 177\,(100) & 147\,(15) & 163\,(10) & 161\,(10) & 177\,(4) & 177\,(2) & 147\,(3) & 163\,(1) & 161\,(3) &  &  \\ 
  18 & $\mathrm{1{,}4B^+{-}2H{-}H_{2}O}$ &  & 145\,(5) &  &  &  &  & 145\,(7) &  &  &  &  & 145\,(1) &  &  &  \\ 
  19 & $\mathrm{1{,}4B^+{-}2H{-}CO}$ & 119\,(3) & 135\,(1) & 133\,(4) &  &  & 119\,(32) & 135\,(29) & 133\,(36) & 149\,(15) & 149\,(11) & 119\,(34) & 135\,(16) & 133\,(36) & 149\,(5) & 149\,(3) \\ 
  20 & $\mathrm{1{,}4B^+{-}2H{-}CO{-}CH_{3}}$ &  &  &  &  &  &  &  & 118\,(11) & 134\,(11) & 134\,(7) &  &  & 118\,(57) & 134\,(20) & 134\,(13) \\ 
%  21 & $\mathrm{1{,}4B^+{-}2H{-}CO{-}CH_{2}O}$ &  &  &  &  &  &  &  & 103\,(6) &  &  &  &  & 103\,(27) &  &  \\ 
  22 & $\mathrm{1{,}4B^+{-}2H{-}2CO}$ &  &  &  &  &  & 91\,(24) &  &  &  &  & 91\,(100) &  &  &  &  \\ 
  23 & $\mathrm{1{,}4B^+{-}2H{-}2CO{-}CH_{3}}$ &  &  &  &  &  &  &  & 90\,(3) &  &  &  &  & 90\,(49) &  &  \\ 
  24 & $\mathrm{1{,}4B^+{-}2H{-}C_{2}H_{2}O{-}H_{2}O}$ &  &  &  &  &  &  &  &  & 117\,(15) & 117\,(32) &  &  &  & 117\,(13) & 117\,(26) \\ 
  25 & $\mathrm{1{,}4B^+{-}2H{-}H_{2}O{-}CO}$ &  &  &  &  &  &  & 117\,(18) &  &  &  &  & 117\,(21) &  &  &  \\ 
  26 & $\mathrm{C_{7}H_{7}^+}$ &  &  &  &  &  & 91\,(24) &  & 91\,(1) & 91\,(3) & 91\,(2) & 91\,(100) &  & 91\,(5) & 91\,(7) & 91\,(5) \\ 
  27 & $\mathrm{C_{7}H_{5}^+}$ &  &  &  &  &  &  & 89\,(23) &  & 89\,(29) & 89\,(24) &  & 89\,(100) & 89\,(22) & 89\,(100) & 89\,(100) \\ 
 % 28 & $\mathrm{C_{5}H_{5}O^+}$ &  &  &  &  &  &  &  &  &  &  & 81\,(1) & 81\,(1) & 81\,(1) & 81\,(2) & 81\,(1) \\ 
   \bottomrule
\end{tabular}
}
\end{sidewaystable}

\begin{sidewaystable}\centering\caption{Key ions in the positive mode CID and HCD ESI-MS\tup{2} spectra of flavones.}
   \label{tab:x_flavonfrag}{\scriptsize%\tiny
\begin{tabular}{ll|ccccc|ccccc|ccccc}
  \toprule
&  \multirow{2}{*}{fragment} & \multicolumn{5}{c}{\textbf{CID, \SI{45}{\percent} NCE}} & \multicolumn{5}{c}{\textbf{HCD, \SI{75}{\percent} NCE}} & \multicolumn{5}{c}{\textbf{HCD, \SI{100}{\percent} NCE}} \\
%& & apigenin & luteolin & acacetin & chrysoeriol & diosmetin & apigenin & luteolin & acacetin & chrysoeriol & diosmetin & apigenin & luteolin & acacetin & chrysoeriol & diosmetin \\
    & & (\textbf{6}) & (\textbf{7}) & (\textbf{8}) & (\textbf{9}) & (\textbf{10}) & (\textbf{6}) & (\textbf{7}) & (\textbf{8}) & (\textbf{9}) & (\textbf{10}) & (\textbf{6}) & (\textbf{6}) & (\textbf{7}) & (\textbf{9}) & (\textbf{10}) \\
  % & \begin{sideways} fragment \end{sideways} & \begin{sideways} apigenin\_CID.45 \end{sideways} & \begin{sideways} luteolin\_CID.45 \end{sideways} & \begin{sideways} acacetin\_CID.45 \end{sideways} & \begin{sideways} diosmetin\_CID.45 \end{sideways} & \begin{sideways} chrysoeriol\_CID.45 \end{sideways} & \begin{sideways} apigenin\_HCD.75 \end{sideways} & \begin{sideways} luteolin\_HCD.75 \end{sideways} & \begin{sideways} acacetin\_HCD.75 \end{sideways} & \begin{sideways} diosmetin\_HCD.75 \end{sideways} & \begin{sideways} chrysoeriol\_HCD.75 \end{sideways} & \begin{sideways} apigenin\_HCD.100 \end{sideways} & \begin{sideways} luteolin\_HCD.100 \end{sideways} & \begin{sideways} acacetin\_HCD.100 \end{sideways} & \begin{sideways} diosmetin\_HCD.100 \end{sideways} & \begin{sideways} chrysoeriol\_HCD.100 \end{sideways} \\ 
  \midrule
1 & $\mathrm{[M{+}H]^+}$ & 271\,(2) &  &  &  &  & 271\,(84) & 287\,(66) & 285\,(4) &  &  & 271\,(2) & 287\,(2) &  &  &  \\ 
  2 & $\mathrm{[M{+}H{-}CH_{3}]^{\bullet+}}$ &  &  & 270\,(100) & 286\,(100) & 286\,(100) &  &  & 270\,(9) & 286\,(20) & 286\,(18) &  &  &  &  &  \\ 
  3 & $\mathrm{[M{+}H{-}H_{2}O]^+}$ & 253\,(1) & 269\,(9) &  &  &  & 253\,(3) & 269\,(6) &  &  &  &  &  &  &  &  \\ 
  4 & $\mathrm{[M{+}H{-}CO]^+}$ & 243\,(7) & 259\,(9) &  &  &  & 243\,(7) &  &  &  &  & 243\,(2) &  &  &  &  \\ 
  5 & $\mathrm{[M{+}H{-}CHO]^{\bullet+}}$ & 242\,(14) & 258\,(47) &  &  &  & 242\,(1) & 258\,(3) &  &  &  & 242\,(2) & 258\,(2) &  &  &  \\ 
  6 & $\mathrm{[M{+}H{-}C_{2}H_{2}O]^+}$ & 229\,(21) & 245\,(13) & 243\,(1) &  &  & 229\,(4) &  &  &  &  &  &  &  &  &  \\ 
  7 & $\mathrm{[M{+}H{-}CH_{3}{-}CO]^{\bullet+}}$ &  &  & 242\,(7) &  &  &  &  & 242\,(100) & 258\,(100) & 258\,(100) &  &  & 242\,(49) & 258\,(49) & 258\,(46) \\ 
  8 & $\mathrm{[M{+}H{-}CH_{4}{-}CO]^+}$ &  &  &  &  &  &  &  & 241\,(1) & 257\,(7) & 257\,(7) &  &  & 241\,(7) & 257\,(38) & 257\,(37) \\ 
  9 & $\mathrm{[M{+}H{-}H_{2}O{-}CO]^+}$ & 225\,(13) & 241\,(13) &  &  &  & 225\,(4) & 241\,(16) &  &  &  &  & 241\,(4) &  &  &  \\ 
%  10 & $\mathrm{[M{+}H{-}2CO]^+}$ &  & 231\,(2) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%  11 & $\mathrm{[M{+}H{-}CH_{3}OH{-}CO]^{\bullet+}}$ &  & 227\,(3) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
%  12 & $\mathrm{[M{+}H{-}CH_{3}{-}2CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  & 216\,(1) &  &  &  \\ 
%  13 & $\mathrm{[M{+}H{-}H_{2}O{-}CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  & 229\,(12) & 229\,(13) &  &  & 213\,(6) & 229\,(75) & 229\,(76) \\ 
  14 & $\mathrm{[M{+}H{-}CH_{4}{-}2CO]^+}$ &  &  &  &  &  &  &  &  & 229\,(12) & 229\,(13) &  &  & 213\,(6) & 229\,(75) & 229\,(76) \\ 
  15 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO]^+}$ &  & 213\,(2) &  &  &  & 197\,(4) & 213\,(7) &  &  &  & 197\,(3) & 213\,(4) &  &  &  \\ 
  16 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O]^+}$ & 187\,(3) & 203\,(4) &  &  &  & 187\,(2) & 203\,(2) &  &  &  & 187\,(1) & 203\,(3) &  &  &  \\ 
  17 & $\mathrm{[M{+}H{-}CH_{3}OH{-}2CO]^{\bullet+}}$ &  &  &  &  &  &  & 199\,(1) &  &  &  &  &  &  & 213\,(4) & 213\,(4) \\ 
  18 & $\mathrm{[M{+}H{-}CH_4{-}2CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 203\,(29) & 203\,(31) \\ 
%  19 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  &  &  &  & 187\,(2) & 185\,(1) & 201\,(7) & 201\,(6) \\ 
  20 & $\mathrm{[M{+}H{-}CH_{4}{-}3CO]^+}$ &  &  &  &  &  &  &  &  &  &  &  & 187\,(2) & 185\,(1) & 201\,(7) & 201\,(6) \\ 
%  21 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O{-}H_{2}O]^+}$ &  &  &  &  &  &  &  &  &  &  & 169\,(2) & 185\,(2) &  &  &  \\ 
%  22 & $\mathrm{[M{+}H{-}CH_{4}{-}2CO{-}C_{2}H_{2}O]^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 187\,(6) & 187\,(5) \\ 
  23 & $\mathrm{[M{+}H{-}CH_{4}{-}4CO]^+}$ &  &  &  &  &  &  &  &  &  &  & 143\,(1) &  &  & 173\,(3) & 173\,(2) \\ 
  24 & $\mathrm{[M{+}H{-}2CO{-}2C_{2}H_{2}O]^+}$ &  &  &  &  &  & 131\,(2) & 147\,(1) &  &  &  & 131\,(5) & 147\,(3) &  & 161\,(4) & 161\,(5) \\ 
 % 26 & $\mathrm{0{,}3A^+}$ &  & 137\,(7) &  &  &  &  & 137\,(12) &  &  &  &  & 137\,(16) &  & 137\,(1) & 137\,(2) \\ 
  27 & $\mathrm{0{,}4B^+}$ & 163\,(6) & 179\,(7) &  &  &  & 163\,(8) & 179\,(3) &  &  &  & 163\,(2) &  &  &  &  \\ 
  28 & $\mathrm{0{,}4B^+{-}H_{2}O}$ & 145\,(13) & 161\,(12) &  &  &  & 145\,(17) & 161\,(16) &  &  &  & 145\,(41) & 161\,(29) &  &  &  \\ 
  25 & $\mathrm{0{,}4B^+{-}C_2H_2O}$ & 121\,(6) & 137\,(7) &  &  &  & 121\,(16) & 137\,(12) &  &  &  & 121\,(25) & 137\,(16) &  &  &  \\ 
  29 & $\mathrm{1{,}3A^+}$ & 153\,(100) & 153\,(100) & 153\,(5) &  &  & 153\,(100) & 153\,(100) & 153\,(11) & 153\,(8) & 153\,(8) & 153\,(84) & 153\,(87) & 153\,(100) & 153\,(100) & 153\,(100) \\ 
  30 & $\mathrm{1{,}3A^+{-}CO}$ &  &  &  &  &  & 125\,(1) & 125\,(2) &  &  &  & 125\,(3) & 125\,(2) &  &  &  \\ 
  31 & $\mathrm{1{,}3A^+{-}C_{2}H_{2}O}$ &  &  &  &  &  & 111\,(2) & 111\,(2) &  &  &  & 111\,(4) & 111\,(3) &  & 111\,(1) & 111\,(1) \\ 
  32 & $\mathrm{1{,}3A^+{-}2CO}$ &  &  &  &  &  & 97\,(2) & 97\,(2) &  &  &  & 97\,(9) & 97\,(9) & 97\,(1) & 97\,(2) & 97\,(2) \\ 
  33 & $\mathrm{1{,}3A^+{-}2CO{-}C_{2}H_{4}}$ &  &  &  &  &  & 69\,(4) & 69\,(5) &  &  &  & 69\,(24) & 69\,(22) & 69\,(1) & 69\,(2) & 69\,(2) \\ 
  34 & $\mathrm{1{,}3B^+}$ & 119\,(12) & 135\,(11) & 133\,(2) &  &  & 119\,(49) & 135\,(40) & 133\,(3) &  &  & 119\,(35) &  &  &  &  \\ 
  35 & $\mathrm{1{,}4A^+{+}2H}$ &  &  &  &  &  &  & 127\,(1) &  &  &  &  & 127\,(2) &  &  &  \\ 
%  36 & $\mathrm{1{,}4A^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  & 124\,(2) & 124\,(4) & 124\,(4) & 124\,(5) \\ 
 % 37 & $\mathrm{1{,}4A^+}$ &  &  &  &  &  & 125\,(1) & 125\,(2) &  &  &  & 125\,(3) & 125\,(2) &  &  &  \\ 
 % 38 & $\mathrm{C_{7}H_{6}O_{5}^+}$ &  &  &  &  &  &  &  &  &  &  &  &  & 170\,(1) & 170\,(1) & 170\,(1) \\ 
  39 & $\mathrm{C_{7}H_{7}^+}$ & 91\,(1) &  &  &  &  & 91\,(26) &  &  &  &  & 91\,(100)  &  &  &  &  \\ 
  40 & $\mathrm{C_{7}H_{5}^+}$ &  &  &  &  &  &  & 89\,(17) &  &  &  & 89\,(7) & 89\,(100) & 89\,(3) &  & 89\,(1) \\ 
%  41 & $\mathrm{C_{5}H_{5}O^+}$ &  &  &  &  &  & 81\,(1) & 81\,(2) &  &  &  & 81\,(3) & 81\,(8) &  &  &  \\ 
   \bottomrule
\end{tabular}
}
\end{sidewaystable}

\begin{sidewaystable}\centering\caption{Key ions in the positive mode CID and HCD ESI-MS\tup{2} spectra of flavonoles.}
  \label{tab:x_flavonolfrag}{\scriptsize%\tiny
\begin{tabular}{ll|ccccc|ccccc|ccccc}
  \toprule
&  \multirow{2}{*}{fragment} & \multicolumn{5}{c}{\textbf{CID, \SI{45}{\percent} NCE}} & \multicolumn{5}{c}{\textbf{HCD, \SI{75}{\percent} NCE}} & \multicolumn{5}{c}{\textbf{HCD, \SI{100}{\percent} NCE}} \\
%& & kaempferol & quercetin & myricetin & kaempferide & isorhamnoside & kaempferol & quercetin & myricetin & kaempferide & isorhamnoside & kaempferol & quercetin & myricetin & kaempferide & isorhamnoside\\
    & & (\textbf{11}) & (\textbf{12}) & (\textbf{13}) & (\textbf{14}) & (\textbf{15}) & (\textbf{11}) & (\textbf{12}) & (\textbf{13}) & (\textbf{14}) & (\textbf{15}) & (\textbf{11}) & (\textbf{12}) & (\textbf{13}) & (\textbf{14}) & (\textbf{15}) \\
  % & \begin{sideways} fragment \end{sideways} & \begin{sideways} kaempferol\_CID.45 \end{sideways} & \begin{sideways} quercetin\_CID.45 \end{sideways} & \begin{sideways} myricetin\_CID.45 \end{sideways} & \begin{sideways} kaempferide\_CID.45 \end{sideways} & \begin{sideways} isorhamnetin\_CID.45 \end{sideways} & \begin{sideways} kaempferol\_HCD.75 \end{sideways} & \begin{sideways} quercetin\_HCD.75 \end{sideways} & \begin{sideways} myricetin\_HCD.75 \end{sideways} & \begin{sideways} kaempferide\_HCD.75 \end{sideways} & \begin{sideways} isorhamnetin\_HCD.75 \end{sideways} & \begin{sideways} kaempferol\_HCD.100 \end{sideways} & \begin{sideways} quercetin\_HCD.100 \end{sideways} & \begin{sideways} myricetin\_HCD.100 \end{sideways} & \begin{sideways} kaempferide\_HCD.100 \end{sideways} & \begin{sideways} isorhamnetin\_HCD.100 \end{sideways} \\ 
  \midrule
1 & $\mathrm{[M{+}H]^+}$ &  &  &  &  &  & 287\,(25) & 303\,(8) & 319\,(1) & 301\,(9) &  &  &  &  &  &  \\ 
  2 & $\mathrm{[M{+}H{-}CH_{3}]^{\bullet+}}$ &  &  &  & 286\,(62) & 302\,(100) &  &  &  & 286\,(12) & 302\,(6) &  &  &  &  &  \\ 
  3 & $\mathrm{[M{+}H{-}CH_{4}]^+}$ &  &  &  & 285\,(2) &  &  &  &  & 285\,(5) & 301\,(3) &  &  &  & 285\,(1) &  \\ 
  4 & $\mathrm{[M{+}H{-}H_{2}O]^+}$ & 269\,(32) & 285\,(63) & 301\,(40) & 283\,(2) & 299\,(3) & 269\,(2) & 285\,(6) & 301\,(1) &  &  & 269\,(2) & 285\,(3) &  &  &  \\ 
  5 & $\mathrm{[M{+}H{-}CO]^+}$ & 259\,(24) & 275\,(14) & 291\,(6) & 273\,(3) &  & 259\,(3) &  &  &  &  &  &  &  &  &  \\ 
  6 & $\mathrm{[M{+}H{-}CHO]^{\bullet+}}$ & 258\,(46) & 274\,(20) & 290\,(22) & 272\,(20) & 288\,(3) & 258\,(10) & 274\,(4) &  & 272\,(2) &  &  &  &  &  &  \\ 
  7 & $\mathrm{[M{+}H{-}CH_{3}OH]^{\bullet+}}$ &  &  &  & 269\,(11) & 285\,(36) &  &  &  & 269\,(11) & 285\,(11) &  &  &  & 269\,(3) & 285\,(3) \\ 
%  8 & $\mathrm{[M{+}H{-}2H_{2}O]^+}$ &  &  & 283\,(4) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  9 & $\mathrm{[M{+}H{-}C_{2}H_{2}O]^+}$ & 245\,(4) &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  10 & $\mathrm{[M{+}H{-}CH_{3}{-}CO]^{\bullet+}}$ &  &  &  & 258\,(9) & 274\,(5) &  &  &  & 258\,(58) & 274\,(6) &  &  &  & 258\,(2) &  \\ 
%  11 & $\mathrm{[M{+}H{-}CO_{2}]^+}$ & 243\,(5) &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  12 & $\mathrm{[M{+}H{-}CH_{4}{-}CO]^+}$ &  &  &  & 257\,(3) &  &  &  &  & 257\,(17) & 273\,(13) &  &  &  & 257\,(6) & 273\,(2) \\ 
  13 & $\mathrm{[M{+}H{-}H_{2}O{-}CO]^+}$ & 241\,(99) & 257\,(100) & 273\,(100) & 255\,(3) & 271\,(5) & 241\,(5) & 257\,(13) & 273\,(6) &  &  & 241\,(1) & 257\,(2) &  &  &  \\ 
  14 & $\mathrm{[M{+}H{-}2CO]^+}$ & 231\,(40) & 247\,(37) & 263\,(25) & 245\,(17) & 261\,(8) & 231\,(5) & 247\,(2) &  &  &  &  &  &  &  &  \\ 
  15 & $\mathrm{[M{+}H{-}CH_{3}OH{-}CO]^{\bullet+}}$ &  &  &  & 241\,(16) & 257\,(8) &  &  &  & 241\,(2) & 257\,(7) &  &  &  &  & 257\,(2) \\ 
 % 16 & $\mathrm{[M{+}H{-}CH_{3}{-}H_{2}O{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  & 240\,(2) & 256\,(2) &  &  &  &  &  \\ 
  17 & $\mathrm{[M{+}H{-}CH_{3}{-}2CO]^{\bullet+}}$ &  &  &  &  &  & 216\,(2) & 232\,(2) &  & 230\,(94) & 246\,(9) & 216\,(2) &  &  & 230\,(9) &  \\ 
 % 18 & $\mathrm{[M{+}H{-}H_{2}O{-}CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  & 229\,(100) & 245\,(42) &  &  &  & 229\,(100) & 245\,(34) \\ 
  19 & $\mathrm{[M{+}H{-}CH_{4}{-}2CO]^+}$ &  &  &  &  &  &  &  &  & 229\,(100) & 245\,(42) &  &  &  & 229\,(100) & 245\,(34) \\ 
  20 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO]^+}$ & 213\,(77) & 229\,(70) & 245\,(32) & 227\,(2) & 243\,(2) & 213\,(20) & 229\,(49) & 245\,(22) & 227\,(2) &  & 213\,(12) & 229\,(16) & 245\,(6) &  &  \\ 
  21 & $\mathrm{[M{+}H{-}3CO]^+}$ &  &  &  &  &  & 203\,(2) &  & 235\,(2) &  &  &  &  &  &  &  \\ 
  22 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O]^+}$ & 203\,(7) & 219\,(4) & 235\,(4) & 217\,(2) &  &  & 219\,(1) &  &  &  & 203\,(1) & 219\,(2) &  &  &  \\ 
    23 & $\mathrm{[M{+}H{-}H_2O{-}CO{-}C_2H_2O]^{\bullet+}}$ & 199\,(3) & 215\,(2) & 231\,(2) & 213\,(4) & 229\,(3) &  &  & 231\,(1) & 213\,(11) & 229\,(33) &  &  &  & 213\,(10) & 229\,(15) \\ 
  23 & $\mathrm{[M{+}H{-}CH_{3}OH{-}2CO]^{\bullet+}}$ &  &  &  & 213\,(4) & 229\,(3) &  &  &  & 213\,(11) & 229\,(33) &  &  &  & 213\,(10) & 229\,(15) \\ 
  24 & $\mathrm{[M{+}H{-}CH_4{-}2CO{-}2C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  & 203\,(3) & 219\,(7) &  &  &  & 203\,(11) & 219\,(13) \\ 
  25 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  & 203\,(3) & 219\,(8) & 201\,(25) & 217\,(41) & 187\,(2) & 203\,(10) & 219\,(21) & 201\,(50) & 217\,(56) \\ 
  26 & $\mathrm{[M{+}H{-}CH_{4}{-}3CO]^+}$ &  &  &  &  &  &  &  &  & 201\,(25) & 217\,(41) &  &  &  & 201\,(50) & 217\,(56) \\ 
  27 & $\mathrm{[M{+}H{-}CH_{4}{-}2CO{-}C_{2}H_{2}O]^+}$ &  &  &  &  &  &  &  &  & 187\,(4) & 203\,(18) &  &  &  & 187\,(13) & 203\,(37) \\ 
  28 & $\mathrm{[M{+}H{-}CH_{4}{-}4CO]^+}$ &  &  &  &  &  &  &  &  & 173\,(2) & 189\,(4) &  &  &  & 173\,(13) & 189\,(11) \\ 
  29 & $\mathrm{[M{+}H{-}2CO{-}2C_{2}H_{2}O]^+}$ & 147\,(13) & 163\,(7) & 179\,(7) & 161\,(13) & 177\,(2) & 147\,(9) & 163\,(7) & 179\,(9) & 161\,(4) &  & 147\,(8) & 163\,(5) & 179\,(9) &  &  \\ 
%  30 & $\mathrm{AC^+}$ &  & 191\,(1) &  &  &  &  & 191\,(2) & 191\,(2) &  & 191\,(1) &  &  & 191\,(2) &  & 191\,(2) \\ 
  31 & $\mathrm{0{,}2A^+}$ & 165\,(100) & 165\,(59) & 165\,(41) & 165\,(31) & 165\,(6) & 165\,(11) & 165\,(9) & 165\,(6) & 165\,(6) & 165\,(1) & 165\,(2) & 165\,(3) & 165\,(4) & 165\,(2) & 165\,(1) \\ 
  32 & $\mathrm{0{,}2A^+{-}CO}$ & 137\,(11) & 137\,(23) & 137\,(6) & 137\,(4) &  & 137\,(14) & 137\,(47) & 137\,(15) & 137\,(7) & 137\,(4) & 137\,(12) & 137\,(38) & 137\,(32) & 137\,(8) & 137\,(13) \\ 
  33 & $\mathrm{0{,}2B^+}$ & 121\,(36) & 137\,(23) & 153\,(35) & 135\,(18) & 151\,(2) &  & 137\,(47) & 153\,(100) & 135\,(14) & 151\,(2) & 121\,(69) & 137\,(38) & 153\,(100) & 135\,(5) & 151\,(1) \\ 
%  34 & $\mathrm{0{,}3A^+}$ & 137\,(11) & 137\,(23) & 137\,(6) & 137\,(4) &  & 137\,(14) & 137\,(47) & 137\,(15) & 137\,(7) & 137\,(4) & 137\,(12) & 137\,(38) & 137\,(32) & 137\,(8) & 137\,(13) \\ 
  35 & $\mathrm{0{,}3A^+{+}2H}$ &  &  &  & 139\,(100) & 139\,(9) &  &  & 139\,(3) & 139\,(7) & 139\,(1) &  &  & 139\,(3) & 139\,(4)  &  \\ 
%  36 & $\mathrm{0{,}4A^+{+}2H}$ &  &  &  & 111\,(1) &  &  &  &  &  &  &  &  &  &  &  \\ 
  37 & $\mathrm{1{,}3A^+}$ & 153\,(61) & 153\,(20) & 153\,(35) & 153\,(28) & 153\,(4) &  & 153\,(100) & 153\,(100) & 153\,(65) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(67) & 153\,(100) \\ 
  38 & $\mathrm{1{,}3A^+{-}CO}$ &  &  &  &  &  &  &  & 125\,(3) &  &  & 125\,(2) & 125\,(1) & 125\,(5) &  &  \\ 
  39 & $\mathrm{1{,}3A^+{-}C_{2}H_{2}O}$ & 111\,(19) & 111\,(7) & 111\,(4) &  &  & 111\,(5) & 111\,(6) & 111\,(6) & 111\,(1) &  & 111\,(4) & 111\,(5) & 111\,(7) & 111\,(3) & 111\,(6) \\ 
  40 & $\mathrm{1{,}3A^+{-}2CO}$ &  &  &  &  &  & 97\,(2) & 97\,(2) & 97\,(3) &  &  & 97\,(9) & 97\,(10) & 97\,(14) & 97\,(3) & 97\,(3) \\ 
  41 & $\mathrm{1{,}3A^+{-}2CO{-}C_{2}H_{4}}$ &  &  &  &  &  & 69\,(7) & 69\,(8) & 69\,(8) & 69\,(3) & 69\,(1) & 69\,(33) & 69\,(31) & 69\,(29) & 69\,(10) & 69\,(8) \\ 
  42 & $\mathrm{1{,}3B^+{-}2H}$ & 133\,(25) & 149\,(10) & 165\,(41) &  & 163\,(2) & 133\,(3) & 149\,(3) & 165\,(6) &  & 163\,(1) & 133\,(1) & 149\,(4) & 165\,(4) & 147\,(3) & 163\,(5) \\ 
%  43 & $\mathrm{1{,}4A^+{+}2H}$ & 127\,(2) & 127\,(1) & 127\,(4) &  &  & 127\,(1) & 127\,(3) & 127\,(2) &  &  & 127\,(2) & 127\,(6) & 127\,(4) &  &  \\ 
%  44 & $\mathrm{1{,}4A^{\bullet+}}$ &  &  &  &  &  &  &  & 124\,(2) & 124\,(11) & 124\,(3) & 124\,(1) & 124\,(3) & 124\,(15) & 124\,(42) & 124\,(14) \\ 
%  45 & $\mathrm{1{,}4A^+}$ &  &  &  &  &  &  &  & 125\,(3) &  &  & 125\,(2) & 125\,(1) & 125\,(5) &  &  \\ 
%  46 & $\mathrm{1{,}4B^+{+}2H}$ &  &  &  &  &  &  & 145\,(2) & 161\,(2) &  &  &  & 145\,(4) & 161\,(4) &  & 159\,(2) \\ 
%  47 & $\mathrm{1{,}4B^+{+}2H{-}H_{2}O}$ & 147\,(13) &  &  & 161\,(13) &  & 147\,(9) &  &  & 161\,(4) &  & 147\,(8) &  &  &  &  \\ 
%  48 & $\mathrm{C_{7}H_{6}O_{5}^+}$ &  &  &  &  &  &  &  & 170\,(1) & 170\,(10) & 170\,(2) &  &  & 170\,(3) & 170\,(8) & 170\,(3) \\ 
  49 & $\mathrm{C_{7}H_{7}^+}$ &  &  &  &  &  & 91\,(2) & 91\,(2) & 91\,(2) & 91\,(4) &  &  &  &  &  &  \\ 
  50 & $\mathrm{C_{7}H_{5}^+}$ &  &  &  &  &  &  &  &  &  &  & 89\,(6) & 89\,(9) & 89\,(7) & 89\,(2) & 89\,(2) \\ 
%  51 & $\mathrm{C_{5}H_{5}O^+}$ &  &  &  &  &  & 81\,(3) & 81\,(8) & 81\,(5) & 81\,(1) & 81\,(1) & 81\,(12) & 81\,(39) & 81\,(24) & 81\,(4) & 81\,(7) \\ 
   \bottomrule
\end{tabular}
}
\end{sidewaystable}
}
