%%%-------------------------------------------------%%%
%%% Sub document for appendix %%%
%%%-------------------------------------------------%%%

\part{Appendix}

\chapter{Figures}

\section{Chapter 3}

\begin{figure}[htpb]
  \centering
  \begin{figureframe}
<<litSAM, eval=T, echo=F, tidy=TRUE, fig.height=5, fig.width=5, out.width='0.7\\textwidth', dev='pdf', error=T, crop=T>>=
@ 
  \end{figureframe}
  \caption{%
    Graphical representation of the work that has been done on \glspl{mt} in combination with \gls{sam} analogues.
    The grey areas represent individual groups of \gls{sam} analogues (aliphatic, allylic, propargylic, aromatic, \gls{seam} analogues, nitrogen analogues and miscelaneous others). 
    The height of the grey areas represents the number of times a member of the corresponding group has been described as tested in the \gls{mt} literature.
    The height of the colored bars represents the times that individual substrate has been tested. The colors represent the different types of \gls{mt} (red -- \gls{dmt}, green -- \gls{pmt}, lilac -- small molecule \gls{mt}, blue -- \gls{rna} \gls{mt}).
    The black dash across the bar shows the number of times this substrate was actually converted by either enzyme.%    
}
  \label{fig:d_lit_sam}
\end{figure}


\begin{figure}[htpb]
  \centering
  \begin{figureframe}
    <<struct.compare.appendix,  echo=F, tidy=TRUE, fig.height=2, fig.width=5.6, out.width='\\textwidth', dev='tikz', error=T>>=
    @
  \end{figureframe}
  \caption{Differences in the dihedrals \textpsi~(red) and \textphi~(black) of the solved \textit{apo}-PFOMT and the structure with bound \gls{sah} (pdb: 3C3Y).
  The secondary structure is displayed at the top. Helices are displayed as rectangles and sheets are shown as arrows.
  Graphical background annotations are used to display the binding sites of \gls{sah} (green) and the metal ion (plum).
  The orange bars indicate regions, where much movement seems to happen upon binding or release of the co-substrate.
  The blue bar shows the region that was annotated as "insertion loop" in previous studies.}
  \label{fig:app_struc.compare}
\end{figure}  


\begin{figure}[htpb]
  \centering
  \begin{figureframe}
    \includegraphics[width=0.5\textwidth]{usr/graphics/static/pfomt_3to4_activities}
  \end{figureframe}
  \caption{Differences in the regioselectivity of some \pfomt variants. The products observed in \gls{hplc} and \gls{lcms} measurements switched from 3'-methylated (dark grey) to 4'-methylated (light grey) for the displayed variants.}
  \label{fig:app_pfomt_3to4}
\end{figure}  

\clearpage
\section{Chapter 4}

\begin{figure}[htpb]
  \centering
  \begin{figureframe}
    \includegraphics[width=0.9\textwidth]{usr/graphics/static/tmp_pca1}
  \end{figureframe}
  \caption{\gls{pca} of \nico leaves infiltraded by \agro carrying different genes.}
  \label{fig:x_pca}
\end{figure}


\begin{figure}[htpb]
  \centering
  \begin{figureframe}
    \includegraphics[width=0.45\textwidth]{usr/graphics/static/sds_somt}
  \end{figureframe}
  \caption{\sdspage gel of samples aquired during growth curve measurements. The arrow indicated the band that could correspond to the GST-tagged \somt protein.}
  \label{fig:x_somtgel}
\end{figure}

\begin{figure}[htpb]
  \centering
  \begin{figureframe}
    \includegraphics[width=0.85\textwidth]{usr/graphics/static/SOMT_SS-bridges}
  \end{figureframe}
  \caption{Graphical representation of a \somt model obtained from the PHYRE2 web portal (\url{http://www.sbg.bio.ic.ac.uk/phyre2/html/page.cgi?id=index}) \citep{Kelley2015}}
  \label{fig:x_somtmodel}
\end{figure}


\begin{figure}[htpb]
  \centering
  \begin{figureframe}
    \includegraphics[width=0.75\textwidth]{usr/graphics/static/platzhalter}
  \end{figureframe}
  \caption{Chromatogram of the gel filtration analysis of refolded \somt.}
  \label{fig:x_somt_gefi}
\end{figure}

%% CD spectrum of SOMT
\begin{figure}[htpb]
  \centering
  \begin{figureframe}
    \includegraphics[width=0.75\textwidth]{usr/graphics/static/CD_SOMT}
  \end{figureframe}
  \caption{CD-spectrum of refolded \somt (black) compared to the spectrum that was calculated by the K2D3 web service (\url{http://cbdm-01.zdv.uni-mainz.de/~andrade/k2d3//index.html}). Secondary structure estimates from the spectrum are \SI{12.39}{\percent} \textalpha-helix and \SI{32.51}{\percent} \textbeta-sheet.}
  \label{fig:x_somt_cd}
\end{figure}


%% Main effects plot PFOMT conversion of non-catechols
\begin{figure}[htpb]
  \centering
  \begin{figureframe}
    \begin{subfigure}{0.73\textwidth}
      \includegraphics[width=\textwidth]{usr/graphics/static/tmp_MEP_pfomt}
      \caption{Main effects plot for PFOMT conversion of non-catechols. 
        Phenolics (A) are converted worst and conversion of \gls{3o4m} is generally best.
        There seem to be positive effects of \cf{Mg^2+} and pH.
        The wild-type enzyme shows better conversion than the 4'-specific variant.}
      \label{fig:x_mep_pfomt}
    \end{subfigure}
    %% Interaction plot Mg/pH
    \begin{subfigure}{0.23\textwidth}
      \includegraphics[width=\textwidth]{usr/graphics/static/tmp_pfomt_MgpH}
      \caption{Interaction plot of \cf{Mg^2+} and pH for the conversion of non-catechols and catechols by \pfomt.
        There seems to be an interaction between \cf{Mg^2+} addition and pH. However, statistical tests suggest this interaction might not be significant.\\
        blue -- \cf{Mg^2+} addition, red -- no \cf{Mg^2+}}
      \label{fig:x_iap_pfomt}
    \end{subfigure}
  \end{figureframe}
  \caption{}
\end{figure}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%% Tables
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\chapter{Tables}

%% Table of cloned constructs (appendix)
\ostTableEnv|[label = tab:molecularcloning]{%
  \scriptsize
  \begin{tabularx}{\textwidth}{l p{0.35\textwidth} p{0.1\textwidth} l X}
    \toprule
    construct name & description & entry constructs & destination & workflow steps (primers/cloning sites)\\ 
    \midrule
    pBEW101 & & & & \\
    pBEW102 & lsrA promoter & & & \\
    pBEW103 & pBEW102 with BamHI cloning site & pBEW102 & & \\
    pBEW104 & rhaP$_{\mathrm{BAD}}$ promoter & pBEW4b & pBEW103 & amplification (\textit{pRha1.fw/rv}), cloning (BglII, BamHI)\\
    pBEW106 & pICH413038-somt & pET28MC-somt & pICH413038 & amplification (\textit{somt1/2/3/4}), golden gate cloning (BpiI) \\
    pBEW107 & & pICH51266, pBEW106, pICH41421 & pICH75044 & golden gate cloning (BsaI) \\
    pBEW1a & & & & \\
    pBEW1b & & & & \\
    pBEW2a & & & & \\
    pBEW2b & & & & \\
    pBEW3a & & & & \\
    pBEW3b & & & & \\
    pBEW4a & & & & \\
    pBEW4b & & & & \\
    pET28-pfomt & \textit{pfomt} gene in pET-28a(+), endogenous NdeI site removed & pQE30-pfomt & pET-28a(+) & mutagenesis (\emph{pfomt1.fw/rv}), amplification (\emph{pfomt2.fw/rv}), cloning (NdeI, EcoRI) \\
    pET20-somt & N-terminal pelB-tag fusion for periplasmic expression & & pET20-b(+)& \\
    pET28-somt & & & pET28-a(+)& \\
    pET28MC-somt & & &  & \\
    pET32-somt & N-terminal TrX-tag fusion & & pET-32a(+) & \\
    pET41-somt & N-terminal GST-tag fusion & & pET-41a(+) & \\
    pUC19* & added BglII site & pUC19 & - & mutagenesis (\textit{pUC1.fw/rv}) \\
    pUCB1 & pUC19 derivative with lsrA promoter & lsr-XX-DAS & pUC19* & cloning (NdeI, BglII) \\ 
    pUCB1-sfGFP-DAS+4 & & & & \\
    
    \bottomrule
  \end{tabularx}
}{%
Overview over the contructs produced for the present thesis. Each step during the production of the construct is given in the workflow steps column. Primers (italic font) or restriction sites used during each step are displayed in parenthesis.
}
% }}}

\begin{lstTabularx}[1]{\linewidth}{>{\scriptsize}p{0.45\textwidth}XX>{\scriptsize}p{0.12\textwidth}}
  \caption{\gls{sam} analogues that have been used with \glspl{mt}. Targets: \emph{P} -- peptide/protein, \emph{D} -- DNA, \emph{R} -- RNA, \emph{S} -- small molecule.} \\
  \label{tab:mtlit}
  \hfill \\
     \toprule
	\small analogue & enzyme & target & \small references \\ 
     \midrule
     \endfirsthead
     \toprule
	\small analogue & enzyme & target & \small references \\ 
     \midrule
     \endhead
     \small\textit{SAM} & & &\\
    % \cf{-CH3} & & &\\
     \cf{-CH2-CH3} & PRMT1, M.TaqI, M.HhaI, M.BcnIB, RebM, RapM & S,P,D & \citep{Thomsen2013,Dalhoff2006,Singh2014,Law2015} \footnote{Singh \etal (2014) published a series of 44 biocatalytically synthesized \gls{sam} and \gls{seam} derivatives, most of which were not tested towards their alkyl donation potential in \gls{mt} reactions.}\\
     \cf{-CH2-CH2-CH3} & PRMT1, M.TaqI, M.HhaI, M.BcnIB & P,D & \citep{Thomsen2013,Dalhoff2006}\\
     \cf{-CH2-CH2-CH2-CH3} & PRMT1 & P & \citep{Thomsen2013}\\
     \cf{-CH2-C6H5} & NovO, CouO, PRMT1 & S,P & \citep{Stecher2009,Thomsen2013}\\
%    \cf{-CH2-CH2-C6H5} & & & \citep{Thomsen2013}\\ % not tested with MTs
%    \cf{-CH2-CH(-NH2)-COOH} & & & \citep{Thomsen2013}\\ % not tested with Mts
%     \cf{-CH2-C(=O)-NH2} & & & \citep{Thomsen2013}\\ % not tested with Mts
     \cf{-CH2-C(=O)-CH3} & COMT, TPMT, CazF & S & \citep{Lee2010,Winter2013}\\
     
     \cf{-CH2-CH=CH2} & NovO, CouO, RapM, PRMT1, M.TaqI, M.HhaI, M.BcnIB, RebM, Tgs & P,S,D & \citep{Stecher2009,Thomsen2013,Dalhoff2006,Singh2014,Wang2011,Wang2011a,Tengg2012a,Law2015,Schulz2013} \\
     \cf{-CH2-CH=CH-CH3} & NovO, CouO & S & \citep{Stecher2009}\\
  %  \cf{-CH2-CH=CH-CH2-CH3} & & & \citep{Wang2014}\\ %% only SAM synthase
    
     \cf{-CH2-C#CH} & Dim-5, \textit{Hs}MLL, TRM1, NovO, CouO, PRMT1 & P,R,S & \citep{Willnow2012,Stecher2009,Wang2011,Wang2011a,Islam2011}\\
     \cf{-CH2-C#N} & RebM & S & \citep{Singh2014} \\
     \cf{-CH2-CH2-C#CH} & PKMT & P & \citep{Islam2011}\\
     \cf{-CH2-CH2-CH2-C#CH} & PKMT & P & \citep{Islam2011}\\
     \cf{-CH2-C#C-CH3} & NovO, CouO, M.HhaI, M.TaqI, M.BcnIB & S,D & \citep{Stecher2009,Dalhoff2006,Lukinavicius2013}\\
     \cf{-CH2-C#C-CH2-CH3} & M.HhaI & D & \citep{Lukinavicius2013} \\
     \cf{-CH2-C#C-CH2-NH2} & M.HhaI & D & \citep{Lukinavicius2013} \\
     \cf{-CH2-C#C-CH2-NH-C(=O)(-CH2-)3-NH2} & M.HhaI & D & \citep{Lukinavicius2013} \\
     \cf{-CH2-C#C(-CH2-)3-NH2} & M.HhaI & D & \citep{Lukinavicius2013} \\
     \cf{-CH2-C#C(-CH2-)3-NH-C(=O)(-CH2-)3-NH2} & M.HhaI & D & \citep{Lukinavicius2013} \\
     \cf{-CH2-C#C(-CH2-)3-C#CH} & M.HhaI & D & \citep{Lukinavicius2013} \\
     \cf{-CH2-C#C(-CH2-)3-N3} & M.HhaI & D & \citep{Lukinavicius2013} \\
     \cf{-CH2-CH=CH-C#CH} & Dim-5, \textit{Hs}MLL, TRM1, PRMT1, Tgs & P,R & \citep{Willnow2012,Peters2010,Wang2011,Wang2011a,Motorin2011,Islam2011,Schulz2013}\\
     \cf{-CH2-CH=CH-CH2-C#CH} & & & \citep{Wang2011a,Islam2011} \\
     \cf{-CH2-CH=CH-CH2-O-CH2-C#CH} & PRMT1 & P & \citep{Wang2011,Wang2011a}\\
     
    \\
     \small\textit{SeAM} & & &\\
     \cf{-CH3} & & & \\
     \cf{-CH2-C#CH} & Dim-5, \textit{Hs}MLL, TRM1, RebM, CazF & P,R,S & \citep{Willnow2012,Singh2014,Bothwell2012, Winter2013}\\
     
     \\
     \small\textit{N}-mustard derivatives & & &\\
     \cf{-CH2-CH2-I} & RebM & S & \citep{Zhang2006} \\
     
     \bottomrule
\end{lstTabularx}


%\ostTableEnv[label = tab:xtalstat]{%
\begin{table}[htpb]\centering
\begin{tabular}{lll}%
% \caption{Crystallographic data, phasing and refinement statistics.} \\
%  \label{tab:d-xtalstat}
%    \small
%  \hfill \\
    \toprule
    & 140519\_PFOMT  & MC001413-G10.1 \\
    \midrule
 %    \endfirsthead
 %   \toprule
 %   & PFOMT  & \\
 %   \midrule
 %   \endhead
     
    \textit{data collection} &  & \\
    wavelength (\gls{a}) &  & \\
    resolution (\gls{a}) & 1.95  & \\
    total reflections & \num{392368} & \\
    unique reflections & \num{125822} & \\
    completeness (\%) & 99.12 & \\
    $I/\sigma (I)$ & 9.9 & \\
    $R^a_{sym}$ &  & \\
    redundancy &  & \\
    space group & $P2_12_12_1$ & \\
    cell dimensions (\gls{a}) &  & \\
    \textit{a} & 86.16 & 48.88 \\
    \textit{b} & 128 & 71.36 \\
    \textit{c} & 129.3 & 127.80 \\ \\
    
    \textit{refinement} &  & \\
    $R_{\mathrm{work}}$/$R_{\mathrm{free}}$ & 0.21369 / 0.24700 & \\
    \gls{rmsd} bond lengths (\gls{a}) & 0.0199  & \\
    \gls{rmsd} bond angles (°) & 2.0568 & \\
    B-values ($\mathrm{\AA^2}$) & 21.593  & \\
    water &  & \\
    ions &  & \\ \\
     
    \textit{Ramachandran plot} (\%) &  & \\
    favoured & 96.82 & \\
    allowed & 2.38 & \\
    outliers & 0.8 & \\
    \bottomrule
  \end{tabular}
\caption{%
Crystallographic data, phasing and refinement statistics.
}
\label{tab:xtalstat}
\end{table}


\begin{table}[htpb]
  \caption{Coefficients of the model (\ref{eq:cat}) for activity of catecholic methylation. The factor $\factor{Mg}$ is a categorical variable (addition/no addition) and can therefore only be 0 or 1.}
  \label{tab:lm-cat}
  \centering\small
  \begin{tabularx}{\textwidth}{lrrrrr}
    \toprule
    & Estimate & Std. Error & t value & p-value &  \\ 
    \midrule
    $($Intercept) & -421929.9946 & 356063.7085 & -1.18 & 0.2557 &  \\ 
    \factorx{Mg} & -839999.8874 & 503550.1257 & -1.67 & 0.1175 &  \\ 
    \factorx{pH} & 103271.3345 & 97739.1728 & 1.06 & 0.3086 &  \\ 
    $\factor{pH^2}$ & -4977.7406 & 6512.6996 & -0.76 & 0.4574 &  \\ 
    \factorx{Mg}$\times$\factorx{pH} & 266920.7964 & 138224.0638 & 1.93 & 0.0740 & . \\ 
    \factorx{Mg}$\times\factor{pH^2}$ & -19830.2264 & 9210.3481 & -2.15 & 0.0492 & * \\ 
    \bottomrule
  \end{tabularx}
\end{table}

\begin{table}
  \caption{Coefficients obtained for linear regression model suing the \ifa subset after shrinkage using the Lasso method and 5-fold cross validation. Only non-zero coefficients (variables actually do have an effect) are retained during the Lasso. Seed was set to 1337.}
  \label{tab:lasso-ifa}
  \centering\small
  \begin{tabularx}{\textwidth}{lr}
    \toprule
    variable & coefficient \\ 
    \midrule
    $($Intercept) & -509.8385 \\ 
    \factorx{pH} & 73.4085 \\ 
    \factorx{Mg} & -1606.1362 \\ 
    \factorx{pH}$\times$\factorx{Mg} & 296.0753 \\ 
    \bottomrule
  \end{tabularx}
\end{table}

\begin{table}
  \caption{Coefficients obtained for linear regression model using the catechols subset after shrinkage using the Lasso method and 5-fold cross validation. Only non-zero coefficients (variables actually do have an effect) are retained during the Lasso. Seed was set to 1336.} 
  \label{tab:lasso-catechol}
  \centering\small
  \begin{tabularx}{\textwidth}{lr}
    \toprule
    variable & coefficient \\ 
    \midrule
    $($Intercept) & -467632.3821 \\ 
    \factorx{pH} & 94469.8366  \\ 
    \factorx{pH}$\times$\factorx{Mg} & 19068.9540 \\ 
    \factorx{pH}$\times\factor{pH^2}$ & -381.5863 \\ 
    \factorx{pH}$\times$\factorx{Mg}$\times\factor{pH^2}$ & -292.3608 \\ 
    \bottomrule
  \end{tabularx}
\end{table}

\clearpage
\section{Chapter 6}

%%%%%%%%%%%%%%%%%% Fragmentation tables

{\setlength\tabcolsep{1.5pt}

\begin{sidewaystable}\caption{Key ions in the positive \gls{esi}-MS\textsuperscript{2} spectra of the flavonoids \molref{naringenin}--\molref{isorhamnetin} using \gls{cid} at \SI{45}{\percent} \gls{nce}.}\centering{\tiny
\label{tab:x_CIDfrag}
    \begin{tabular}{ll|ccccc|ccccc|ccccc}
  \toprule
& fragment & \molnum{naringenin} & \molnum{ed} & \molnum{ponciretin} & \molnum{hesperetin} & \molnum{hed} & \molnum{apigenin} & \molnum{luteolin} & \molnum{acacetin} & \molnum{diosmetin} & \molnum{chrysoeriol} & \molnum{kaempferol} & \molnum{quercetin} & \molnum{myricetin} & \molnum{kaempferide} & \molnum{isorhamnetin} \\
  %& \begin{sideways} fragment \end{sideways} & \begin{sideways} naringenin \end{sideways} & \begin{sideways} eriodictyol \end{sideways} & \begin{sideways} ponciretin \end{sideways} & \begin{sideways} hesperetin \end{sideways} & \begin{sideways} homoeriodictyol \end{sideways} & \begin{sideways} apigenin \end{sideways} & \begin{sideways} luteolin \end{sideways} & \begin{sideways} acacetin \end{sideways} & \begin{sideways} diosmetin \end{sideways} & \begin{sideways} chrysoeriol \end{sideways} & \begin{sideways} kaempferol \end{sideways} & \begin{sideways} quercetin \end{sideways} & \begin{sideways} myricetin \end{sideways} & \begin{sideways} kaempferide \end{sideways} & \begin{sideways} isorhamnetin \end{sideways} \\ 
  \midrule
1 & $\mathrm{[M{+}H]^+}$ &  &  &  &  &  & 271\,(2) &  &  &  &  &  &  &  &  &  \\ 
  2 & $\mathrm{[M{+}H{-}CH_{3}]^{\bullet+}}$ &  &  &  &  &  &  &  & 270\,(100) & 286\,(100) & 286\,(100) &  &  &  & 286\,(62) & 302\,(100) \\ 
  3 & $\mathrm{[M{+}H{-}CH_{4}]^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 285\,(2) &  \\ 
  4 & $\mathrm{[M{+}H{-}H_{2}O]^+}$ & 255\,(1) & 271\,(18) & 269\,(1) & 285\,(10) & 285\,(4) & 253\,(1) & 269\,(9) &  &  &  & 269\,(32) & 285\,(63) & 301\,(40) & 283\,(2) & 299\,(3) \\ 
  5 & $\mathrm{[M{+}H{-}CO]^+}$ &  &  &  &  &  & 243\,(7) & 259\,(9) &  &  &  & 259\,(24) & 275\,(14) & 291\,(6) & 273\,(3) &  \\ 
  6 & $\mathrm{[M{+}H{-}CHO]^{\bullet+}}$ &  &  &  &  &  & 242\,(14) & 258\,(47) &  &  &  & 258\,(46) & 274\,(20) & 290\,(22) & 272\,(20) & 288\,(3) \\ 
  7 & $\mathrm{[M{+}H{-}CH_{3}OH]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 269\,(11) & 285\,(36) \\ 
  8 & $\mathrm{[M{+}H{-}2H_{2}O]^+}$ &  & 253\,(4) &  &  &  &  &  &  &  &  &  &  & 283\,(4) &  &  \\ 
  9 & $\mathrm{[M{+}H{-}C_{2}H_{2}O]^+}$ & 231\,(4) & 247\,(3) & 245\,(3) & 261\,(2) & 261\,(2) & 229\,(21) & 245\,(13) & 243\,(1) &  &  & 245\,(4) &  &  &  &  \\ 
  10 & $\mathrm{[M{+}H{-}CH_{3}{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  & 242\,(7) &  &  &  &  &  & 258\,(9) & 274\,(5) \\ 
  11 & $\mathrm{[M{+}H{-}CO_{2}]^+}$ &  &  &  &  &  &  &  &  &  &  & 243\,(5) &  &  &  &  \\ 
  12 & $\mathrm{[M{+}H{-}CH_{4}{-}CO]^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 257\,(3) &  \\ 
  13 & $\mathrm{[M{+}H{-}H_{2}O{-}CO]^+}$ &  &  &  &  &  & 225\,(13) & 241\,(13) &  &  &  & 241\,(99) & 257\,(100) & 273\,(100) & 255\,(3) & 271\,(5) \\ 
  14 & $\mathrm{[M{+}H{-}2CO]^+}$ &  &  &  &  &  &  & 231\,(2) &  &  &  & 231\,(40) & 247\,(37) & 263\,(25) & 245\,(17) & 261\,(8) \\ 
  15 & $\mathrm{[M{+}H{-}CH_{3}OH{-}CO]^{\bullet+}}$ &  &  &  &  &  &  & 227\,(3) &  &  &  &  &  &  & 241\,(16) & 257\,(8) \\ 
  16 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO]^+}$ &  &  &  &  &  &  & 213\,(2) &  &  &  & 213\,(77) & 229\,(70) & 245\,(32) & 227\,(2) & 243\,(2) \\ 
  17 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O]^+}$ & 189\,(5) & 205\,(3) & 203\,(4) & 219\,(2) & 219\,(1) & 187\,(3) & 203\,(4) &  &  &  & 203\,(7) & 219\,(4) & 235\,(4) & 217\,(2) &  \\ 
  18 & $\mathrm{[M{+}H{-}CH_{3}OH{-}2CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  & 199\,(3) & 215\,(2) & 231\,(2) & 213\,(4) & 229\,(3) \\ 
  19 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O{-}H_{2}O]^+}$ &  & 187\,(4) &  & 201\,(1) &  &  &  &  &  &  &  &  &  &  &  \\ 
  20 & $\mathrm{[M{+}H{-}2CO{-}2C_{2}H_{2}O]^+}$ &  &  &  &  &  &  &  &  &  &  & 147\,(13) & 163\,(7) & 179\,(7) & 161\,(13) & 177\,(2) \\ 
  21 & $\mathrm{AC^+}$ & 179\,(4) & 179\,(20) & 179\,(5) & 179\,(28) & 179\,(30) &  &  &  &  &  &  & 191\,(1) &  &  &  \\ 
  22 & $\mathrm{0{,}2A^+}$ &  &  &  &  &  &  &  &  &  &  & 165\,(100) & 165\,(59) & 165\,(41) & 165\,(31) & 165\,(6) \\ 
  23 & $\mathrm{0{,}2A^+{-}CO}$ &  &  &  &  &  &  &  &  &  &  & 137\,(11) & 137\,(23) & 137\,(6) & 137\,(4) &  \\ 
  24 & $\mathrm{0{,}2B^+}$ &  &  &  &  &  & 121\,(6) & 137\,(7) &  &  &  & 121\,(36) & 137\,(23) & 153\,(35) & 135\,(18) & 151\,(2) \\ 
  25 & $\mathrm{0{,}3A^+}$ &  &  &  &  &  &  & 137\,(7) &  &  &  & 137\,(11) & 137\,(23) & 137\,(6) & 137\,(4) &  \\ 
  26 & $\mathrm{0{,}3A^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 139\,(100) & 139\,(9) \\ 
  27 & $\mathrm{0{,}4A^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 111\,(1) &  \\ 
  28 & $\mathrm{0{,}4B^+}$ &  &  &  &  &  & 163\,(6) & 179\,(7) &  &  &  &  &  &  &  &  \\ 
  29 & $\mathrm{0{,}4B^+{-}H_{2}O}$ &  &  &  &  &  & 145\,(13) &  &  &  &  &  &  &  &  &  \\ 
  30 & $\mathrm{1{,}3A^+}$ & 153\,(100) & 153\,(31) & 153\,(77) & 153\,(21) & 153\,(57) & 153\,(100) & 153\,(100) & 153\,(5) &  &  & 153\,(61) & 153\,(20) & 153\,(35) & 153\,(28) & 153\,(4) \\ 
  31 & $\mathrm{1{,}3A^+{-}C_{2}H_{2}O}$ &  &  &  &  &  &  &  &  &  &  & 111\,(19) & 111\,(7) & 111\,(4) &  &  \\ 
  32 & $\mathrm{1{,}3B^+}$ &  &  &  &  &  & 119\,(12) & 135\,(11) & 133\,(2) &  &  &  &  &  &  &  \\ 
  33 & $\mathrm{1{,}3B^+{-}2H}$ &  &  &  &  &  &  &  &  &  &  & 133\,(25) & 149\,(10) & 165\,(41) &  & 163\,(2) \\ 
  34 & $\mathrm{1{,}4A^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  & 127\,(2) & 127\,(1) & 127\,(4) &  &  \\ 
  35 & $\mathrm{1{,}4B^+{-}2H}$ & 147\,(84) & 163\,(100) & 161\,(100) & 177\,(100) & 177\,(100) &  &  &  &  &  &  &  &  &  &  \\ 
  36 & $\mathrm{1{,}4B^+{+}2H{-}H_{2}O}$ &  &  &  &  &  &  &  &  &  &  & 147\,(13) &  &  & 161\,(13) &  \\ 
  37 & $\mathrm{1{,}4B^+{-}2H{-}H_{2}O}$ &  & 145\,(5) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  38 & $\mathrm{1{,}4B^+{-}2H{-}CO}$ & 119\,(3) & 135\,(1) & 133\,(4) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  39 & $\mathrm{C_{7}H_{7}^+}$ &  &  &  &  &  & 91\,(1) &  &  &  &  &  &  &  &  &  \\ 
   \bottomrule
\end{tabular}
}
\end{sidewaystable}

\begin{sidewaystable}\caption{Key ions in the positive \gls{esi}-MS\textsuperscript{2} spectra of the flavonoids \molref{naringenin}--\molref{isorhamnetin} using \gls{hcd} at \SI{75}{\percent} \gls{nce}.}\centering{\tiny
\label{tab:x_HCD75frag}
    \begin{tabular}{ll|ccccc|ccccc|ccccc}
  \toprule
& fragment & \molref*{naringenin} & \molref*{ed} & \molref*{ponciretin} & \molref*{hesperetin} & \molref*{hed} & \molref*{apigenin} & \molref*{luteolin} & \molref*{acacetin} & \molref*{diosmetin} & \molref*{chrysoeriol} & \molref*{kaempferol} & \molref*{quercetin} & \molref*{myricetin} & \molref*{kaempferide} & \molref*{isorhamnetin} \\
  %  & \begin{sideways} fragment \end{sideways} & \begin{sideways} naringenin \end{sideways} & \begin{sideways} eriodictyol \end{sideways} & \begin{sideways} ponciretin \end{sideways} & \begin{sideways} hesperetin \end{sideways} & \begin{sideways} homoeriodictyol \end{sideways} & \begin{sideways} apigenin \end{sideways} & \begin{sideways} luteolin \end{sideways} & \begin{sideways} acacetin \end{sideways} & \begin{sideways} diosmetin \end{sideways} & \begin{sideways} chrysoeriol \end{sideways} & \begin{sideways} kaempferol \end{sideways} & \begin{sideways} quercetin \end{sideways} & \begin{sideways} myricetin \end{sideways} & \begin{sideways} kaempferide \end{sideways} & \begin{sideways} isorhamnetin \end{sideways} \\ 
  \midrule
1 & $\mathrm{[M{+}H]^+}$ &  &  &  &  &  & 271\,(84) & 287\,(66) & 285\,(4) &  &  & 287\,(25) & 303\,(8) & 319\,(1) & 301\,(9) &  \\ 
  2 & $\mathrm{[M{+}H{-}CH_{3}]^{\bullet+}}$ &  &  &  &  &  &  &  & 270\,(9) & 286\,(20) & 286\,(18) &  &  &  & 286\,(12) & 302\,(6) \\ 
  3 & $\mathrm{[M{+}H{-}CH_{4}]^+}$ &  &  &  & 287\,(1) &  &  &  &  &  &  &  &  &  & 285\,(5) & 301\,(3) \\ 
  4 & $\mathrm{[M{+}H{-}H_{2}O]^+}$ &  &  &  &  &  & 253\,(3) & 269\,(6) &  &  &  & 269\,(2) & 285\,(6) & 301\,(1) &  &  \\ 
  5 & $\mathrm{[M{+}H{-}CO]^+}$ &  &  &  &  &  & 243\,(7) &  &  &  &  & 259\,(3) &  &  &  &  \\ 
  6 & $\mathrm{[M{+}H{-}CHO]^{\bullet+}}$ &  &  &  &  &  & 242\,(1) & 258\,(3) &  &  &  & 258\,(10) & 274\,(4) &  & 272\,(2) &  \\ 
  7 & $\mathrm{[M{+}H{-}CH_{3}OH]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 269\,(11) & 285\,(11) \\ 
  8 & $\mathrm{[M{+}H{-}C_{2}H_{2}O]^+}$ &  &  &  &  &  & 229\,(4) &  &  &  &  &  &  &  &  &  \\ 
  9 & $\mathrm{[M{+}H{-}CH_{3}{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  & 242\,(100) & 258\,(100) & 258\,(100) &  &  &  & 258\,(58) & 274\,(6) \\ 
  10 & $\mathrm{[M{+}H{-}CH_{4}{-}CO]^+}$ &  &  &  &  &  &  &  & 241\,(1) & 257\,(7) & 257\,(7) &  &  &  & 257\,(17) & 273\,(13) \\ 
  11 & $\mathrm{[M{+}H{-}H_{2}O{-}CO]^+}$ &  &  &  &  &  & 225\,(4) & 241\,(16) &  &  &  & 241\,(5) & 257\,(13) & 273\,(6) &  &  \\ 
  12 & $\mathrm{[M{+}H{-}2CO]^+}$ &  &  &  &  &  &  &  &  &  &  & 231\,(5) & 247\,(2) &  &  &  \\ 
  13 & $\mathrm{[M{+}H{-}CH_{3}OH{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 241\,(2) & 257\,(7) \\ 
  14 & $\mathrm{[M{+}H{-}CH_{3}{-}H_{2}O{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 240\,(2) & 256\,(2) \\ 
  15 & $\mathrm{[M{+}H{-}CH_{3}{-}2CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  & 216\,(2) & 232\,(2) &  & 230\,(94) & 246\,(9) \\ 
  16 & $\mathrm{[M{+}H{-}H_{2}O{-}CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  & 229\,(12) & 229\,(13) &  &  &  & 229\,(100) & 245\,(42) \\ 
  17 & $\mathrm{[M{+}H{-}CH_{4}{-}2CO]^+}$ &  &  &  &  &  &  &  &  & 229\,(12) & 229\,(13) &  &  &  & 229\,(100) & 245\,(42) \\ 
  18 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO]^+}$ &  &  &  &  &  & 197\,(4) & 213\,(7) &  &  &  & 213\,(20) & 229\,(49) & 245\,(22) & 227\,(2) &  \\ 
  19 & $\mathrm{[M{+}H{-}3CO]^+}$ &  &  &  &  &  &  &  &  &  &  & 203\,(2) &  & 235\,(2) &  &  \\ 
  20 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O]^+}$ &  &  &  &  &  & 187\,(2) & 203\,(2) &  &  &  &  & 219\,(1) &  &  &  \\ 
  21 & $\mathrm{[M{+}H{-}CH_{3}OH{-}2CO]^{\bullet+}}$ &  &  &  &  &  &  & 199\,(1) &  &  &  &  &  & 231\,(1) & 213\,(11) & 229\,(33) \\ 
  22 & $\mathrm{[M{+}H{-}H_{2}O{-}CO{-}2C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 203\,(3) & 219\,(7) \\ 
  23 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  &  &  &  & 203\,(3) & 219\,(8) & 201\,(25) & 217\,(41) \\ 
  24 & $\mathrm{[M{+}H{-}CH_{4}{-}3CO]^+}$ &  &  &  &  &  &  &  &  &  &  &  & 203\,(3) & 219\,(8) & 201\,(25) & 217\,(41) \\ 
  25 & $\mathrm{[M{+}H{-}CH_{4}{-}2CO{-}C_{2}H_{2}O]^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 187\,(4) & 203\,(18) \\ 
  26 & $\mathrm{[M{+}H{-}2CO{-}2C_{2}H_{2}O]^+}$ &  &  &  &  &  & 131\,(2) & 147\,(1) &  &  &  & 147\,(9) & 163\,(7) & 179\,(9) & 161\,(4) &  \\ 
  27 & $\mathrm{AC^+}$ &  & 179\,(1) &  & 179\,(2) & 179\,(2) &  &  &  &  &  &  & 191\,(2) & 191\,(2) &  & 191\,(1) \\ 
  28 & $\mathrm{0{,}2A^+}$ &  &  &  &  &  &  &  &  &  &  & 165\,(11) & 165\,(9) & 165\,(6) & 165\,(6) & 165\,(1) \\ 
  29 & $\mathrm{0{,}2A^+{-}CO}$ &  &  &  &  &  &  &  &  &  &  & 137\,(14) & 137\,(47) & 137\,(15) & 137\,(7) & 137\,(4) \\ 
  30 & $\mathrm{0{,}2B^+}$ &  &  &  &  &  & 121\,(16) & 137\,(12) &  &  &  &  & 137\,(47) & 153\,(100) & 135\,(14) & 151\,(2) \\ 
  31 & $\mathrm{0{,}3A^+}$ &  &  &  &  &  &  & 137\,(12) &  &  &  & 137\,(14) & 137\,(47) & 137\,(15) & 137\,(7) & 137\,(4) \\ 
  32 & $\mathrm{0{,}3A^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  &  &  & 139\,(3) & 139\,(7) & 139\,(1) \\ 
  33 & $\mathrm{0{,}4A^+{+}2H}$ &  &  &  &  & 111\,(2) &  &  &  &  &  &  &  &  &  &  \\ 
  34 & $\mathrm{0{,}4B^+}$ &  &  &  &  &  & 163\,(8) & 179\,(3) &  &  &  &  &  &  &  &  \\ 
  35 & $\mathrm{0{,}4B^+{-}H_{2}O}$ &  &  &  &  &  & 145\,(17) & 161\,(16) &  &  &  &  &  &  &  &  \\ 
  36 & $\mathrm{1{,}3A^+}$ & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(11) & 153\,(8) & 153\,(8) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(65) & 153\,(100) \\ 
  37 & $\mathrm{1{,}3A^+{-}CO}$ &  &  &  &  &  & 125\,(1) & 125\,(2) &  &  &  &  &  & 125\,(3) &  &  \\ 
  38 & $\mathrm{1{,}3A^+{-}C_{2}H_{2}O}$ &  & 111\,(2) & 111\,(1) & 111\,(1) &  & 111\,(2) & 111\,(2) &  &  &  & 111\,(5) & 111\,(6) & 111\,(6) & 111\,(1) &  \\ 
  39 & $\mathrm{1{,}3A^+{-}2CO}$ & 97\,(3) & 97\,(4) & 97\,(3) & 97\,(4) & 97\,(4) & 97\,(2) & 97\,(2) &  &  &  & 97\,(2) & 97\,(2) & 97\,(3) &  &  \\ 
  40 & $\mathrm{1{,}3A^+{-}2CO{-}C_{2}H_{4}}$ & 69\,(2) & 69\,(2) & 69\,(2) & 69\,(2) & 69\,(2) & 69\,(4) & 69\,(5) &  &  &  & 69\,(7) & 69\,(8) & 69\,(8) & 69\,(3) & 69\,(1) \\ 
  41 & $\mathrm{1{,}3B^+}$ &  &  &  &  &  & 119\,(49) & 135\,(40) & 133\,(3) &  &  &  &  &  &  &  \\ 
  42 & $\mathrm{1{,}3B^+{-}2H}$ &  &  &  &  &  &  &  &  &  &  & 133\,(3) & 149\,(3) & 165\,(6) &  & 163\,(1) \\ 
  43 & $\mathrm{1{,}4A^+{+}2H}$ &  &  &  &  &  &  & 127\,(1) &  &  &  & 127\,(1) & 127\,(3) & 127\,(2) &  &  \\ 
  44 & $\mathrm{1{,}4A^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  & 124\,(2) & 124\,(11) & 124\,(3) \\ 
  45 & $\mathrm{1{,}4A^+}$ &  &  &  &  &  & 125\,(1) & 125\,(2) &  &  &  &  &  & 125\,(3) &  &  \\ 
  46 & $\mathrm{1{,}4B^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  &  & 145\,(2) & 161\,(2) &  &  \\ 
  47 & $\mathrm{1{,}4B^+{-}2H}$ & 147\,(15) & 163\,(10) & 161\,(10) & 177\,(4) & 177\,(2) &  &  &  &  &  &  &  &  &  &  \\ 
  48 & $\mathrm{1{,}4B^+{+}2H{-}H_{2}O}$ &  &  &  &  &  &  &  &  &  &  & 147\,(9) &  &  & 161\,(4) &  \\ 
  49 & $\mathrm{1{,}4B^+{-}2H{-}H_{2}O}$ &  & 145\,(7) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  50 & $\mathrm{1{,}4B^+{-}2H{-}CO}$ & 119\,(32) & 135\,(29) & 133\,(36) & 149\,(15) & 149\,(11) &  &  &  &  &  &  &  &  &  &  \\ 
  51 & $\mathrm{1{,}4B^+{-}2H{-}CO{-}CH_{3}}$ &  &  & 118\,(11) & 134\,(11) & 134\,(7) &  &  &  &  &  &  &  &  &  &  \\ 
  52 & $\mathrm{1{,}4B^+{-}2H{-}CO{-}CH_{2}O}$ &  &  & 103\,(6) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  53 & $\mathrm{1{,}4B^+{-}2H{-}2CO}$ & 91\,(24) &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  54 & $\mathrm{1{,}4B^+{-}2H{-}2CO{-}CH_{3}}$ &  &  & 90\,(3) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  55 & $\mathrm{1{,}4B^+{-}2H{-}C_{2}H_{2}O{-}H_{2}O}$ &  &  &  & 117\,(15) & 117\,(32) &  &  &  &  &  &  &  &  &  &  \\ 
  56 & $\mathrm{1{,}4B^+{-}2H{-}H_{2}O{-}CO}$ &  & 117\,(18) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  57 & $\mathrm{C_{7}H_{6}O_{5}^+}$ &  &  &  &  &  &  &  &  &  &  &  &  & 170\,(1) & 170\,(10) & 170\,(2) \\ 
  58 & $\mathrm{C_{7}H_{7}^+}$ & 91\,(24) &  & 91\,(1) & 91\,(3) & 91\,(2) & 91\,(26) &  &  &  &  & 91\,(2) & 91\,(2) & 91\,(2) & 91\,(4) &  \\ 
  59 & $\mathrm{C_{7}H_{5}^+}$ &  & 89\,(23) &  & 89\,(29) & 89\,(24) &  & 89\,(17) &  &  &  &  &  &  &  &  \\ 
  60 & $\mathrm{C_{5}H_{5}O^+}$ &  &  &  &  &  & 81\,(1) & 81\,(2) &  &  &  & 81\,(3) & 81\,(8) & 81\,(5) & 81\,(1) & 81\,(1) \\ 
   \bottomrule
\end{tabular}
}
\end{sidewaystable}


\begin{sidewaystable}\caption{Key ions in the positive \gls{esi}-MS\textsuperscript{2} spectra of the flavonoids \molref{naringenin}--\molref{isorhamnetin} using \gls{hcd} at \SI{100}{\percent} \gls{nce}.}\centering{\tiny
\label{tab:x_HCD100frag}
    \begin{tabular}{ll|ccccc|ccccc|ccccc}
  \toprule
& fragment & \molref*{naringenin} & \molref*{ed} & \molref*{ponciretin} & \molref*{hesperetin} & \molref*{hed} & \molref*{apigenin} & \molref*{luteolin} & \molref*{acacetin} & \molref*{diosmetin} & \molref*{chrysoeriol} & \molref*{kaempferol} & \molref*{quercetin} & \molref*{myricetin} & \molref*{kaempferide} & \molref*{isorhamnetin} \\
  % & \begin{sideways} fragment \end{sideways} & \begin{sideways} naringenin \end{sideways} & \begin{sideways} eriodictyol \end{sideways} & \begin{sideways} ponciretin \end{sideways} & \begin{sideways} hesperetin \end{sideways} & \begin{sideways} homoeriodictyol \end{sideways} & \begin{sideways} apigenin \end{sideways} & \begin{sideways} luteolin \end{sideways} & \begin{sideways} acacetin \end{sideways} & \begin{sideways} diosmetin \end{sideways} & \begin{sideways} chrysoeriol \end{sideways} & \begin{sideways} kaempferol \end{sideways} & \begin{sideways} quercetin \end{sideways} & \begin{sideways} myricetin \end{sideways} & \begin{sideways} kaempferide \end{sideways} & \begin{sideways} isorhamnetin \end{sideways} \\ 
  \midrule
1 & $\mathrm{[M{+}H]^+}$ &  &  &  &  &  & 271\,(2) & 287\,(2) &  &  &  &  &  &  &  &  \\ 
  2 & $\mathrm{[M{+}H{-}CH_{4}]^+}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 285\,(1) &  \\ 
  3 & $\mathrm{[M{+}H{-}H_{2}O]^+}$ &  &  &  &  &  &  &  &  &  &  & 269\,(2) & 285\,(3) &  &  &  \\ 
  4 & $\mathrm{[M{+}H{-}CO]^+}$ &  &  &  &  &  & 243\,(2) &  &  &  &  &  &  &  &  &  \\ 
  5 & $\mathrm{[M{+}H{-}CHO]^{\bullet+}}$ &  &  &  &  &  & 242\,(2) & 258\,(2) &  &  &  &  &  &  &  &  \\ 
  6 & $\mathrm{[M{+}H{-}CH_{3}OH]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  &  & 269\,(3) & 285\,(3) \\ 
  7 & $\mathrm{[M{+}H{-}CH_{3}{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  & 242\,(49) & 258\,(49) & 258\,(46) &  &  &  & 258\,(2) &  \\ 
  8 & $\mathrm{[M{+}H{-}CH_{4}{-}CO]^+}$ &  &  &  &  &  &  &  & 241\,(7) & 257\,(38) & 257\,(37) &  &  &  & 257\,(6) & 273\,(2) \\ 
  9 & $\mathrm{[M{+}H{-}H_{2}O{-}CO]^+}$ &  &  &  &  &  &  & 241\,(4) &  &  &  & 241\,(1) & 257\,(2) &  &  &  \\ 
  10 & $\mathrm{[M{+}H{-}CH_{3}OH{-}CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  &  &  &  &  &  &  & 257\,(2) \\ 
  11 & $\mathrm{[M{+}H{-}CH_{3}{-}2CO]^{\bullet+}}$ &  &  &  &  &  &  & 216\,(1) &  &  &  & 216\,(2) &  &  & 230\,(9) &  \\ 
  12 & $\mathrm{[M{+}H{-}H_{2}O{-}CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  & 213\,(6) & 229\,(75) & 229\,(76) &  &  &  & 229\,(100) & 245\,(34) \\ 
  13 & $\mathrm{[M{+}H{-}CH_{4}{-}2CO]^+}$ &  &  &  &  &  &  &  & 213\,(6) & 229\,(75) & 229\,(76) &  &  &  & 229\,(100) & 245\,(34) \\ 
  14 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO]^+}$ &  &  &  &  &  & 197\,(3) & 213\,(4) &  &  &  & 213\,(12) & 229\,(16) & 245\,(6) &  &  \\ 
  15 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O]^+}$ &  &  &  &  &  & 187\,(1) & 203\,(3) &  &  &  & 203\,(1) & 219\,(2) &  &  &  \\ 
  16 & $\mathrm{[M{+}H{-}CH_{3}OH{-}2CO]^{\bullet+}}$ &  &  &  &  &  &  &  &  & 213\,(4) & 213\,(4) &  &  &  & 213\,(10) & 229\,(15) \\ 
  17 & $\mathrm{[M{+}H{-}H_{2}O{-}CO{-}2C_{2}H_{2}]^+}$ &  &  &  &  &  &  &  &  & 203\,(29) & 203\,(31) &  &  &  & 203\,(11) & 219\,(13) \\ 
  18 & $\mathrm{[M{+}H{-}H_{2}O{-}2CO{-}C_{2}H_{2}]^+}$ &  &  &  &  &  &  & 187\,(2) & 185\,(1) & 201\,(7) & 201\,(6) & 187\,(2) & 203\,(10) & 219\,(21) & 201\,(50) & 217\,(56) \\ 
  19 & $\mathrm{[M{+}H{-}CH_{4}{-}3CO]^+}$ &  &  &  &  &  &  & 187\,(2) & 185\,(1) & 201\,(7) & 201\,(6) & 187\,(2) & 203\,(10) & 219\,(21) & 201\,(50) & 217\,(56) \\ 
  20 & $\mathrm{[M{+}H{-}2C_{2}H_{2}O{-}H_{2}O]^+}$ &  &  &  &  &  & 169\,(2) & 185\,(2) &  &  &  &  &  &  &  &  \\ 
  21 & $\mathrm{[M{+}H{-}CH_{4}{-}2CO{-}C_{2}H_{2}O]^+}$ &  &  &  &  &  &  &  &  & 187\,(6) & 187\,(5) &  &  &  & 187\,(13) & 203\,(37) \\ 
  22 & $\mathrm{[M{+}H{-}2CO{-}2C_{2}H_{2}O]^+}$ &  &  &  &  &  & 131\,(5) & 147\,(3) &  & 161\,(4) & 161\,(5) & 147\,(8) & 163\,(5) & 179\,(9) &  &  \\ 
  23 & $\mathrm{AC^+}$ &  &  &  & 179\,(2) & 179\,(1) &  &  &  &  &  &  &  & 191\,(2) &  & 191\,(2) \\ 
  24 & $\mathrm{0{,}2A^+}$ &  &  &  &  &  &  &  &  &  &  & 165\,(2) & 165\,(3) & 165\,(4) & 165\,(2) & 165\,(1) \\ 
  25 & $\mathrm{0{,}2A^+{-}CO}$ &  &  &  &  &  &  &  &  &  &  & 137\,(12) & 137\,(38) & 137\,(32) & 137\,(8) & 137\,(13) \\ 
  26 & $\mathrm{0{,}2B^+}$ &  &  &  &  &  & 121\,(25) & 137\,(16) &  &  &  & 121\,(69) & 137\,(38) & 153\,(100) & 135\,(5) & 151\,(1) \\ 
  27 & $\mathrm{0{,}3A^+}$ &  &  &  & 137\,(3) & 137\,(2) &  & 137\,(16) &  & 137\,(1) & 137\,(2) & 137\,(12) & 137\,(38) & 137\,(32) & 137\,(8) & 137\,(13) \\ 
  28 & $\mathrm{0{,}3A^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  &  &  & 139\,(3) &  &  \\ 
  29 & $\mathrm{0{,}4B^+}$ &  &  &  &  &  & 163\,(2) &  &  &  &  &  &  &  &  &  \\ 
  30 & $\mathrm{0{,}4B^+{-}H_{2}O}$ &  &  &  &  &  & 145\,(41) & 161\,(29) &  &  &  &  &  &  &  &  \\ 
  31 & $\mathrm{1{,}3A^+}$ & 153\,(69) & 153\,(50) & 153\,(100) & 153\,(63) & 153\,(58) & 153\,(84) & 153\,(87) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(100) & 153\,(67) & 153\,(100) \\ 
  32 & $\mathrm{1{,}3A^+{-}CO}$ & 125\,(1) &  & 125\,(1) & 125\,(1) &  & 125\,(3) & 125\,(2) &  &  &  & 125\,(2) & 125\,(1) & 125\,(5) &  &  \\ 
  33 & $\mathrm{1{,}3A^+{-}C_{2}H_{2}O}$ & 111\,(2) & 111\,(2) & 111\,(4) & 111\,(2) & 111\,(2) & 111\,(4) & 111\,(3) &  & 111\,(1) & 111\,(1) & 111\,(4) & 111\,(5) & 111\,(7) & 111\,(3) & 111\,(6) \\ 
  34 & $\mathrm{1{,}3A^+{-}2CO}$ & 97\,(10) & 97\,(8) & 97\,(15) & 97\,(9) & 97\,(9) & 97\,(9) & 97\,(9) & 97\,(1) & 97\,(2) & 97\,(2) & 97\,(9) & 97\,(10) & 97\,(14) & 97\,(3) & 97\,(3) \\ 
  35 & $\mathrm{1{,}3A^+{-}2CO{-}C_{2}H_{4}}$ & 69\,(9) & 69\,(8) & 69\,(13) & 69\,(9) & 69\,(8) & 69\,(24) & 69\,(22) & 69\,(1) & 69\,(2) & 69\,(2) & 69\,(33) & 69\,(31) & 69\,(29) & 69\,(10) & 69\,(8) \\ 
  36 & $\mathrm{1{,}3B^+}$ &  &  &  &  &  & 119\,(35) &  &  &  &  &  &  &  &  &  \\ 
  37 & $\mathrm{1{,}3B^+{-}2H}$ &  &  &  &  &  &  &  &  &  &  & 133\,(1) & 149\,(4) & 165\,(4) & 147\,(3) & 163\,(5) \\ 
  38 & $\mathrm{1{,}4A^+{+}2H}$ &  &  &  &  &  &  & 127\,(2) &  &  &  & 127\,(2) & 127\,(6) & 127\,(4) &  &  \\ 
  39 & $\mathrm{1{,}4A^{\bullet+}}$ &  &  &  &  &  &  & 124\,(2) & 124\,(4) & 124\,(4) & 124\,(5) & 124\,(1) & 124\,(3) & 124\,(15) & 124\,(42) & 124\,(14) \\ 
  40 & $\mathrm{1{,}4A^+}$ & 125\,(1) &  & 125\,(1) & 125\,(1) &  & 125\,(3) & 125\,(2) &  &  &  & 125\,(2) & 125\,(1) & 125\,(5) &  &  \\ 
  41 & $\mathrm{1{,}4B^+{+}2H}$ &  &  &  &  &  &  &  &  &  &  &  & 145\,(4) & 161\,(4) &  & 159\,(2) \\ 
  42 & $\mathrm{1{,}4B^+{-}2H}$ & 147\,(3) & 163\,(1) & 161\,(3) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  43 & $\mathrm{1{,}4B^+{+}2H{-}H_{2}O}$ &  &  &  &  &  &  &  &  &  &  & 147\,(8) &  &  &  &  \\ 
  44 & $\mathrm{1{,}4B^+{-}2H{-}H_{2}O}$ &  & 145\,(1) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  45 & $\mathrm{1{,}4B^+{-}2H{-}CO}$ & 119\,(34) & 135\,(16) & 133\,(36) & 149\,(5) & 149\,(3) &  &  &  &  &  &  &  &  &  &  \\ 
  46 & $\mathrm{1{,}4B^+{-}2H{-}CO{-}CH_{3}}$ &  &  & 118\,(57) & 134\,(20) & 134\,(13) &  &  &  &  &  &  &  &  &  &  \\ 
  47 & $\mathrm{1{,}4B^+{-}2H{-}CO{-}CH_{2}O}$ &  &  & 103\,(27) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  48 & $\mathrm{1{,}4B^+{-}2H{-}2CO}$ & 91\,(100) &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  49 & $\mathrm{1{,}4B^+{-}2H{-}2CO{-}CH_{3}}$ &  &  & 90\,(49) &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  50 & $\mathrm{1{,}4B^+{-}2H{-}C_{2}H_{2}O{-}H_{2}O}$ &  &  &  & 117\,(13) & 117\,(26) &  &  &  &  &  &  &  &  &  &  \\ 
  51 & $\mathrm{1{,}4B^+{-}2H{-}H_{2}O{-}CO}$ &  & 117\,(21) &  &  &  &  &  &  &  &  &  &  &  &  &  \\ 
  52 & $\mathrm{C_{7}H_{6}O_{5}^+}$ &  &  &  &  &  &  &  & 170\,(1) & 170\,(1) & 170\,(1) &  &  & 170\,(3) & 170\,(8) & 170\,(3) \\ 
  53 & $\mathrm{C_{7}H_{7}^+}$ & 91\,(100) &  & 91\,(5) & 91\,(7) & 91\,(5) &  &  &  &  &  &  &  &  &  &  \\ 
  54 & $\mathrm{C_{7}H_{5}^+}$ &  & 89\,(100) & 89\,(22) & 89\,(100) & 89\,(100) & 89\,(7) & 89\,(100) & 89\,(3) &  & 89\,(1) & 89\,(6) & 89\,(9) & 89\,(7) & 89\,(2) & 89\,(2) \\ 
  55 & $\mathrm{C_{5}H_{5}O^+}$ & 81\,(1) & 81\,(1) & 81\,(1) & 81\,(2) & 81\,(1) & 81\,(3) & 81\,(8) &  &  &  & 81\,(12) & 81\,(39) & 81\,(24) & 81\,(4) & 81\,(7) \\ 
   \bottomrule
\end{tabular}
}
\end{sidewaystable}
}

\begin{figure}[htpb]\centering
  \begin{figureframe}  
    \begin{subfigure}{\textwidth}\centering
      \includegraphics[scale=1]{usr/graphics/static/hesperetin_HCD_1,3B}
      \caption{}
      \label{fig:HCD_hesperetin_1.3}
    \end{subfigure}  
    \begin{subfigure}{\textwidth}\centering
      \includegraphics[scale=1]{usr/graphics/static/hesperetin_HCD_1,4B}
      \caption{}
      \label{fig:HCD_hesperetin_1.4}
    \end{subfigure}
  \end{figureframe}
  \caption{Proposed mechanisms for the formation of \textbf{\subref{fig:HCD_hesperetin_1.3}} -- \frag{1,3}{B}{+} and \textbf{\subref{fig:HCD_hesperetin_1.4}} -- \frag{1,4}{B}{+} ions from hesperetin upon \gls{hcd}.}
  \label{fig:mechanism_hcd_hesp}
\end{figure}
