%%%-------------------------------------------------%%%
%%% Sub document bibliography inclusion %%%
%%%-------------------------------------------------%%%

%\chapter{Bibliography}

% \section*{Articles}
% \addcontentsline{toc}{section}{Articles}
%\nocite{*} 
\printbibliography
 \addcontentsline{toc}{chapter}{Bibliography}
% \printbibliography[heading=bibempty]
% \printbibliography[heading=bibempty,type=article]
