%%%-------------------------------------------------%%%
%%% Glossary definitions %%%
%%%-------------------------------------------------%%%


% starts the glossary files creation
\makeglossaries

% analytics
\newacronym[symbol=GC]{gc}{GC}{gas chromatography}
\newacronym[symbol=CD]{cd}{CD}{circulary dichroism}
\newacronym[symbol=FPLC]{fplc}{FPLC}{fast protein liquid chromatography}
\newacronym[symbol=GC/MS]{gcms}{GC/MS}{gas chromatography coupled mass-spectrometry}
\newacronym[symbol=LC/MS]{lcms}{LC/MS}{liquid chromatography coupled mass-spectrometry}
\newacronym[symbol=HPLC]{hplc}{HPLC}{high-performance liquid chromatography}
\newacronym[symbol=NMR]{nmr}{NMR}{nuclear magnetic resonance}
\newacronym{hrp}{HRP}{horseradish peroxidase}
\newacronym[symbol=HRMS]{hrms}{HRMS}{high resolution mass spectrometry}
\newacronym{page}{PAGE}{polyacrylamide gel electrophoresis}
\newacronym{sds}{SDS}{sodium dodecylsulfate}
\newacronym{edta}{EDTA}{ethylenediaminetetraacetic acid}
\newacronym{rt}{RT}{room temperature}
\newacronym{aic}{AIC}{affinity interaction chromatography}
% units
\newacronym[nonumberlist=true, firstplural={minutes (min)}, plural={min}]{min}{min}{minute}
\newacronym[nonumberlist=true]{v}{V}{volume}
\newacronym[nonumberlist]{bper}{B-PER}{bacterial protein extraction reagent}
%\newacronym{sdspage}{sodium dodecylsulfate-polyacrylamid gel elecrtophoresis}%
%\newacronym{pcr}{PCR}{polymerase chain reaction}
% enzymes
%newacronym{pfomt}{PFOMT}{phenylpropanoid and flavonoid O-methyl transferase}
\newacronym{comt}{COMT}{catechol O-methyl transferase}
\newacronym{somt}{SOMT-2}{soy O-methyl transferase}
%\newacronym{des}{DES}{deep eutectic solvent}
% substances
\newacronym{lb}{LB}{lysogeny broth}
\newacronym{tb}{TB}{terrific broth}
\newacronym[plural={inclusion bodies}]{ib}{IBs}{inclusion bodies}
\newacronym{mmt}{MMT}{Mes/malate/Tris}
\newacronym{ssg}{SSG}{succinate/sodium phosphate/glycine}
\newacronym{iptg}{IPTG}{isopropyl-\textsc{D}-thiogalactopyranosid}
\newacronym{tca}{TCA}{trichloro acetic acid}
\newacronym{pbs}{PBS}{phosphate buffered saline}
\newacronym{nta}{NTA}{nitrilo triacetic acid}
\newacronym{mw}{MW}{molecular weight}
\newacronym[nonumberlist]{ipb}{IPB}{Leibniz-Institute of Plant Biochemistry}
\newacronym[nonumberlist]{cv}{CV}{column volumes}


% start your declarations
\newglossaryentry{zyp}{
  type	=	\acronymtype,
  name	=	ZYP,
  text	=	ZYP-5052,
  symbol=	ZYP,
  first	=	{N-\emph{Z}-amine, \emph{y}east extract, \emph{p}hosphate (ZYP-5052)},
% description = {N-Z-amine, yeast extract, phosphate}%
%  description = {N-\emph{Z}-amine, \emph{y}east extract, \emph{p}hosphate}
  description = \glslink{zypg}{N-\protect\emph{Z}-amine, \protect\emph{y}east extract, \protect\emph{p}hosphate}%
}

\newglossaryentry{zypg}{
   name	=	\glslink{zyp}{ZYP-5052},
   description = {%
     Autoinduction medium developed by Studier \citep{Studier2005}. The naming stems from the components N-\protect\emph{Z}-amine, \protect\emph{y}east extract and \protect\emph{p}hosphate. The numbering designates the composition; e.g. 5052 refers to 0.5\,\% glycerol, 0.05\,\% glucose and 0.2\,\% lactose.
   }
}

\newglossaryentry{sah}{
  	type	= \acronymtype,
        name	= SAH,
        text	= SAH,
        symbol	= SAH,
        first	= \protect\textit{S}-adenosyl-textsc{L}-homocysteine (SAH),
        description	= \textit{S}-adenosyl homocysteine%
}

\newglossaryentry{sam}{
  	type	= \acronymtype,
        name	= SAM,
        text	= SAM,
        symbol	= SAM,
        first	= \textit{S}-adenosyl-\textsc{L}-methionine (SAM),
        description	= \textit{S}-adenosyl-\textsc{L}-methionine%
}

\newglossaryentry{pcr}{
  	type	= \acronymtype,
        name	= PCR,
        text	= PCR,
        symbol	= PCR,
        first	= polymerase chain reaction (PCR),
        description	= polymerase chain reaction%
}

\newglossaryentry{des}{
  	type	= \acronymtype,
        name	= DES,
        text	= DES,
        symbol	= DES,
        longplural	= deep eutectic solvents,
        plural	= DES,
        first	= deep eutectic solvent (DES),
        description	= deep eutectic solvent%
}

\newglossaryentry{itc}{
	type        = \acronymtype,
	name        = ITC,
	text        = ITC,
        symbol	    = Isothermal Titration Calorimetry,
	first       = Isothermal Titration Calorimetry (ITC),
%	see         = [see also]{itc},
	description = \glslink{itcg}{Isothermal Titration Calorimetry}
}

\newglossaryentry{itcg}{
	name        = \glslink{itc}{Isothermal Titration Calorimetry (ITC)},
	description = {
		Fill in description here%
	}
}


\newglossaryentry{pfomt}{
	type        = \acronymtype,
	name        = PFOMT,
	text        = PFOMT,
	first       = phenylpropanoid and flavonoid O-methyl transferase (PFOMT),
%	see         = [see also]{itc},
	description = \glslink{pfomtg}{phenylpropanoid and flavonoid O-methyl transferase}
}

\newglossaryentry{pfomtg}{
	name        = \glslink{pfomt}{PFOMT},
	description = {
		Phenylpropanoid and flavonoid O-methyl transferase from \textit{Mesembryanthemum crystallinum}, which was first described by Ibdah et al. in 2003 \citep{Ibdah2003}%
        }
}

\newglossaryentry{mtp}{
	type        = \acronymtype,
	name        = MTP,
	text        = MTP,
        plural	    = MTPs,
        longplural  = micro-titer plates,
	first       = micro-titer plate (MTP),
	description = \glslink{mtpg}{micro-titer plate}
}

\newglossaryentry{mtpg}{
	name        = \glslink{mtp}{MTP},
        plural      = MTPs,
        longplural  = micro-titer plates,
	description = {
		Micro-titer plate. Small format rectangular plastic plate containing wells to allow for storage of multiple small samples or the containment multiple simultaneous reactions. Typical sizes include 24, 96 and 384-wells%
        }
}

\newglossaryentry{tip}{
	type        = \acronymtype,
	name        = Ti-plasmid,
	text        = Ti-plasmid,
        plural	    = Ti-plasmids,
        longplural  = tumor inducing plasmids,
	first       = tumor inducing plasmid (Ti-plasmid),
	description = \glslink{tipg}{tumor inducing plasmid}
}

\newglossaryentry{tipg}{
	name        = \glslink{tip}{Ti-plasmid},
        plural      = Ti-plasmids,
        longplural  = tumor inducing plasmids,
	description = {
		Commonly found plasmids in \textit{A.\,tumefaciens} and \textit{A.\,rhizogenes} that confer virulence%
        }
}

\newglossaryentry{god}{
	type        = \acronymtype,
	name        = GOD,
	text        = GOD,
	first       = glucose oxidase (GOD),
	description = \glslink{godg}{glucose oxidase}
}

\newglossaryentry{godg}{
	name        = \glslink{god}{GOD},
	description = {
		Glucose oxidase is an enzyme....
        }
}

